In [532]:
import pandas as pd
import os
import re
from sklearn.preprocessing import OneHotEncoder

In [533]:
data = pd.read_csv('<file path>/<file name>.csv')
data.head()

/Users/briannahancock/opt/anaconda3/envs/PythonData2/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3457: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [534]:
# Dropping rows with bad data
data = data.drop(labels=[19729,19730,29502,29503,35586,35587], axis=0)

In [535]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45460 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45460 non-null  object
 1   belongs_to_collection  4490 non-null   object
 2   budget                 45460 non-null  object
 3   genres                 45460 non-null  object
 4   homepage               7778 non-null   object
 5   id                     45460 non-null  object
 6   imdb_id                45443 non-null  object
 7   original_language      45449 non-null  object
 8   original_title         45460 non-null  object
 9   overview               44506 non-null  object
 10  popularity             45460 non-null  object
 11  poster_path            45077 non-null  object
 12  production_companies   45460 non-null  object
 13  production_countries   45460 non-null  object
 14  release_date           45376 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.7+ MB

In [536]:
# Dropping columns with lots of null rows, and JSON data types
data = data.drop(columns=['belongs_to_collection', 'homepage', 'overview', 'production_companies', 'production_countries', 'spoken_languages', 'tagline'])

In [537]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45460 entries, 0 to 45465
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   adult              45460 non-null  object
 1   budget             45460 non-null  object
 2   genres             45460 non-null  object
 3   id                 45460 non-null  object
 4   imdb_id            45443 non-null  object
 5   original_language  45449 non-null  object
 6   original_title     45460 non-null  object
 7   popularity         45460 non-null  object
 8   poster_path        45077 non-null  object
 9   release_date       45376 non-null  object
 10  revenue            45460 non-null  float64
 11  runtime            45203 non-null  float64
 12  status             45379 non-null  object
 13  title              45460 non-null  object
 14  video              45460 non-null  object
 15  vote_average       45460 non-null  float64
 16  vote_count         45460 non-null  float64
dtypes: float64(4), object(13)
memory usage: 6.2+ MB

In [538]:
data.columns

Index(['adult', 'budget', 'genres', 'id', 'imdb_id', 'original_language',
       'original_title', 'popularity', 'poster_path', 'release_date',
       'revenue', 'runtime', 'status', 'title', 'video', 'vote_average',
       'vote_count'],
      dtype='object')

In [539]:
imdb = pd.Series(data.imdb_id)
imdb

0        tt0114709
1        tt0113497
2        tt0113228
3        tt0114885
4        tt0113041
           ...
45461    tt6209470
45462    tt2028550
45463    tt0303758
45464    tt0008536
45465    tt6980792
Name: imdb_id, Length: 45460, dtype: object

In [540]:
# Cleaning up imdb id to map to other tables
new_imdb = []
for id in imdb:
    # print(id)
    id = str(id)
    id = id.replace('tt', '')
    new_imdb.append(id)
new_imdb

['0114709',
 '0113497',
 '0113228',
 '0114885',
 '0113041',
 '0113277',
 '0114319',
 '0112302',
 '0114576',
 '0113189',
 '0112346',
 '0112896',
 '0112453',
 '0113987',
 '0112760',
 '0112641',
 '0114388',
 '0113101',
 '0112281',
 '0113845',
 '0113161',
 '0112722',
 '0112401',
 '0114168',
 '0113627',
 '0114057',
 '0114011',
 '0114117',
 '0112682',
 '0115012',
 '0112792',
 '0114746',
 '0114952',
 '0112431',
 '0112637',
 '0112818',
 '0112286',
 '0113442',
 '0112697',
 '0112749',
 '0114279',
 '0112819',
 '0114272',
 '0113855',
 '0114681',
 '0113347',
 '0114369',
 '0114148',
 '0114916',
 '0114814',
 '0109950',
 '0113819',
 '0110299',
 '0112499',
 '0113158',
 '0113541',
 '0113321',
 '0110877',
 '0112714',
 '0113419',
 '0116260',
 '0113862',
 '0116126',
 '0118002',
 '0115683',
 '0116839',
 '0114753',
 '0113149',
 '0113118',
 '0116367',
 '0113010',
 '0113537',
 '0113828',
 '0115644',
 '0115676',
 '0114367',
 '0113973',
 '0112744',
 '0116731',
 '0112445',
 '0114660',
 '0112379',
 '0114039',
 '0113612',
 '0112365',
 '0118158',
 '0116151',
 '0115697',
 '0113972',
 '0113490',
 '0117002',
 '0114825',
 '0115639',
 '0115759',
 '0113403',
 '0113247',
 '0111173',
 '0113283',
 '0115907',
 '0115734',
 '0117102',
 '0118040',
 '0116483',
 '0112579',
 '0110251',
 '0117110',
 '0112646',
 '0113276',
 '0112573',
 '0075314',
 '0113326',
 '0115645',
 '0113774',
 '0112556',
 '0112373',
 '0115033',
 '0116606',
 '0114536',
 '0117427',
 '0106473',
 '0103859',
 '0109424',
 '0114808',
 '0116324',
 '0110647',
 '0111055',
 '0110217',
 '0114131',
 '0112364',
 '0113107',
 '0113451',
 '0114015',
 '0114500',
 '0116130',
 '0113125',
 '0113756',
 '0113952',
 '0114618',
 '0118055',
 '0115685',
 '0113200',
 '0112585',
 '0112442',
 '0112342',
 '0112461',
 '0112427',
 '0109093',
 '0112384',
 '0114287',
 '0112288',
 '0112462',
 '0061395',
 '0112495',
 '0112541',
 '0109370',
 '0112642',
 '0112688',
 '0112715',
 '0112740',
 '0109508',
 '0112851',
 '0112857',
 '0112864',
 '0112887',
 '0113044',
 '0113071',
 '0113114',
 '0113243',
 '0113464',
 '0113481',
 '0113492',
 '0113500',
 '0113540',
 '0113677',
 '0113690',
 '0107447',
 '0113729',
 '0113749',
 '0113820',
 '0113851',
 '0110604',
 '0110620',
 '0113957',
 '0113986',
 '0114095',
 '0114194',
 '0114241',
 '0114323',
 '0114345',
 '0114435',
 '0114436',
 '0114478',
 '0114496',
 '0114508',
 '0114534',
 '0114558',
 '0058450',
 '0114666',
 '0114663',
 '0114702',
 '0114682',
 '0114781',
 '0114798',
 '0114805',
 '0114887',
 '0114898',
 '0114928',
 '0114938',
 '0109340',
 '0112602',
 '0111579',
 '0110882',
 '0112471',
 '0112508',
 '0112438',
 '0112571',
 '0112757',
 '0112643',
 '0112679',
 '0109445',
 '0112883',
 '0109635',
 '0112899',
 '0109676',
 '0112854',
 '0109579',
 '0109642',
 '0109686',
 '0111797',
 '0109759',
 '0109758',
 '0109707',
 '0113117',
 '0113097',
 '0113028',
 '0113198',
 '0113303',
 '0113089',
 '0109771',
 '0113199',
 '0113234',
 '0109906',
 '0110057',
 '0110005',
 '0110066',
 '0110116',
 '0110006',
 '0113360',
 '0110099',
 '0110148',
 '0113463',
 '0110189',
 '0110216',
 '0113501',
 '0113538',
 '0113552',
 '0076759',
 '0110367',
 '0113670',
 '0110296',
 '0109731',
 '0103994',
 '0110322',
 '0110443',
 '0110365',
 '0107566',
 '0110391',
 '0113691',
 '0110428',
 '0109836',
 '0113755',
 '0110538',
 '0110516',
 '0110527',
 '0113808',
 '0113896',
 '0113870',
 '0110684',
 '0110638',
 '0113967',
 '0117169',
 '0106402',
 '0113948',
 '0110671',
 '0110632',
 '0110737',
 '0110729',
 '0114151',
 '0114069',
 '0110413',
 '0114113',
 '0114210',
 '0110912',
 '0114084',
 '0105652',
 '0110889',
 '0110932',
 '0114129',
 '0110963',
 '0114214',
 '0114296',
 '0110907',
 '0111495',
 '0108394',
 '0111507',
 '0110769',
 '0114268',
 '0110965',
 '0114571',
 '0111333',
 '0111112',
 '0111255',
 '0111282',
 '0111070',
 '0111161',
 '0111149',
 '0108260',
 '0106966',
 '0114594',
 '0111309',
 '0113936',
 '0110081',
 '0114614',
 '0114608',
 '0111280',
 '0114609',
 '0111454',
 '0114852',
 '0114694',
 '0111590',
 '0114788',
 '0114888',
 '0108550',
 '0114857',
 '0114924',
 '0111667',
 '0109655',
 '0110598',
 '0112435',
 '0109040',
 '0109045',
 '0106339',
 '0104779',
 '0109348',
 '0109444',
 '0109446',
 '0109484',
 '0109504',
 '0109506',
 '0109450',
 '0109813',
 '0109830',
 '0109831',
 '0113305',
 '0110091',
 '0110093',
 '0110167',
 '0110213',
 '0107472',
 '0110357',
 '0107426',
 '0111686',
 '0110475',
 '0110478',
 '0110588',
 '0110622',
 '0110771',
 '0110950',
 '0105226',
 '0110989',
 '0111054',
 '0110997',
 '0111257',
 '0111256',
 '0111438',
 '0111503',
 '0111693',
 '0111742',
 '0111756',
 '0112443',
 '0110455',
 '0111048',
 '0110399',
 '0112570',
 '0109454',
 '0059170',
 '0110186',
 '0108069',
 '0111301',
 '0112702',
 '0112849',
 '0113014',
 '0113043',
 '0113104',
 '0113173',
 '0113319',
 '0113827',
 '0114047',
 '0112889',
 '0109339',
 '0110027',
 '0109785',
 '0113409',
 '0109021',
 '0109035',
 '0106220',
 '0111804',
 '0106226',
 '0109068',
 '0109067',
 '0106292',
 '0109198',
 '0109219',
 '0106379',
 '0106400',
 '0109254',
 '0109279',
 '0109297',
 '0109303',
 '0109305',
 '0109306',
 '0106452',
 '0106471',
 '0106489',
 '0109361',
 '0106505',
 '0106519',
 '0109439',
 '0109443',
 '0106582',
 '0106598',
 '0109456',
 '0109480',
 '0109493',
 '0106660',
 '0106673',
 '0106677',
 '0106697',
 '0109729',
 '0106834',
 '0106873',
 '0106332',
 '0109783',
 '0106881',
 '0106880',
 '0111732',
 '0106926',
 '0111712',
 '0106941',
 '0106918',
 '0106965',
 '0109842',
 '0106977',
 '0107004',
 '0109890',
 '0109891',
 '0109913',
 '0109920',
 '0107057',
 '0107076',
 '0107096',
 '0107144',
 '0113674',
 '0112966',
 '0107151',
 '0110064',
 '0110074',
 '0110097',
 '0110123',
 '0107206',
 '0107207',
 '0110137',
 '0108551',
 '0110197',
 '0107286',
 '0107290',
 '0107302',
 '0110265',
 '0107322',
 '0110305',
 '0107362',
 '0107413',
 '0110353',
 '0107468',
 '0107478',
 '0107497',
 '0107501',
 '0107507',
 '0107554',
 '0116253',
 '0074102',
 '0111689',
 '0107616',
 '0107611',
 '0107613',
 '0107614',
 '0107653',
 '0110657',
 '0110649',
 '0110678',
 '0110687',
 '0107756',
 '0107808',
 '0107818',
 '0107822',
 '0107840',
 '0107889',
 '0111003',
 '0110939',
 '0110955',
 '0107943',
 '0110971',
 '0107969',
 '0111001',
 '0107978',
 '0107977',
 '0107983',
 '0105275',
 '0108000',
 '0108002',
 '0108026',
 '0105032',
 '0108052',
 '0111094',
 '0108065',
 '0111102',
 '0108071',
 '0111127',
 '0111143',
 '0108101',
 '0108122',
 '0111194',
 '0111201',
 '0108149',
 '0108160',
 '0108162',
 '0083658',
 '0108186',
 '0108174',
 '0108238',
 '0089256',
 '0108255',
 '0111323',
 '0111400',
 '0108328',
 '0111418',
 '0107688',
 '0108333',
 '0108358',
 '0111488',
 '0108399',
 '0108515',
 '0110763',
 '0107779',
 '0109226',
 '0110259',
 '0114906',
 '0107002',
 '0109403',
 '0104029',
 '0110623',
 '0107315',
 '0106408',
 '0110363',
 '0107349',
 '0111709',
 '0109828',
 '0107225',
 '0111252',
 '0110366',
 '0106878',
 '0109120',
 '0108059',
 '0110892',
 '0112651',
 '0107642',
 '0109382',
 '0106678',
 '0112572',
 '0099785',
 '0099653',
 '0103639',
 '0103064',
 '0099348',
 '0114706',
 '0096895',
 '0102926',
 '0029583',
 '0101414',
 '0032910',
 '0100405',
 '0110719',
 '0065214',
 '0110395',
 '0111752',
 '0109934',
 '0112606',
 '0117247',
 '0112625',
 '0106537',
 '0116282',
 '0116552',
 '0082509',
 '0116514',
 '0117283',
 '0116684',
 '0110374',
 '0070506',
 '0065421',
 '0113083',
 '0118001',
 '0116165',
 '0102855',
 '0107471',
 '0113839',
 '0112712',
 '0090665',
 '0117891',
 '0113613',
 '0117381',
 '0114305',
 '0115837',
 '0115509',
 '0114671',
 '0112844',
 '0114658',
 '0116275',
 '0113122',
 '0117608',
 '0113448',
 '0116414',
 '0116095',
 '0111543',
 '0117517',
 '0117312',
 '0116485',
 '0113947',
 '0115956',
 '0117060',
 '0109028',
 '0117071',
 '0117788',
 '0112257',
 '0116136',
 '0118026',
 '0117117',
 '0116168',
 '0111787',
 '0112509',
 '0054189',
 '0115591',
 '0116683',
 '0116287',
 '0116768',
 '0116269',
 '0114787',
 '0113720',
 '0112536',
 '0048473',
 '0052572',
 '0117128',
 '0114616',
 '0117705',
 '0062711',
 '0110061',
 '0140614',
 '0108181',
 '0114307',
 '0058898',
 '0082206',
 '0111430',
 '0107727',
 '0081759',
 '0113443',
 '0109491',
 '0114048',
 '0111613',
 '0117104',
 '0117688',
 '0109751',
 '0117774',
 '0114736',
 '0112604',
 '0116289',
 '0109593',
 '0103095',
 '0112368',
 '0104046',
 '0062952',
 '0115742',
 '0117420',
 '0115951',
 '0117784',
 '0117107',
 '0117979',
 '0095776',
 '0115851',
 '0116322',
 '0109374',
 '0110712',
 '0112817',
 '0113362',
 '0073778',
 '0112546',
 '0108500',
 '0117108',
 '0113270',
 '0333373',
 '0115963',
 '0116448',
 '0116827',
 '0114894',
 '0112701',
 '0113429',
 '0116508',
 '0117260',
 '0117500',
 '0116405',
 '0109592',
 '0117998',
 '0115624',
 '0113145',
 '0116559',
 '0113568',
 '0117894',
 '0117723',
 '0112586',
 '0112691',
 '0040366',
 '0117768',
 '0115571',
 '0031612',
 '0057012',
 '0103926',
 '0105737',
 '0113849',
 '0113188',
 '0042644',
 '0109381',
 '0109688',
 '0104606',
 '0110480',
 '0108211',
 '0117331',
 '0117765',
 '0116833',
 '0113280',
 '0116669',
 '0116594',
 '0113211',
 '0114494',
 '0094265',
 '0105201',
 '0070820',
 '0084898',
 '0063715',
 '0109191',
 '0114122',
 '0117951',
 '0118523',
 '0116629',
 '0117737',
 '0116277',
 '0116583',
 '0115798',
 '0116778',
 '0116213',
 '0113147',
 '0117218',
 '0100990',
 '0111546',
 '0093199',
 '0106810',
 '0111180',
 '0111237',
 '0072362',
 '0103207',
 '0116040',
 '0116365',
 '0116905',
 '0116493',
 '0117333',
 '0118113',
 '0117628',
 '0117913',
 '0115530',
 '0114266',
 '0115493',
 '0116320',
 '0116756',
 '0109356',
 '0116823',
 '0112568',
 '0114170',
 '0117999',
 '0118073',
 '0108220',
 '0049521',
 '0104403',
 '0061495',
 '0110246',
 '0116164',
 '0112865',
 '0112716',
 '0115472',
 '0116707',
 '0116313',
 '0114550',
 '0117438',
 '0116531',
 '0117332',
 '0116353',
 '0115857',
 '0117008',
 '0116191',
 '0115986',
 '0116571',
 '0053459',
 '0117826',
 '0113695',
 '0108227',
 '0111424',
 '0113080',
 '0115680',
 '0117718',
 '0116225',
 '0112767',
 '0115632',
 '0117918',
 '0104109',
 '0051980',
 '0100840',
 '0107575',
 '0042054',
 '0068646',
 '0109255',
 '0104558',
 '0116985',
 '0046468',
 '0114474',
 '0115736',
 '0115836',
 '0101692',
 '0116745',
 '0119214',
 '0116934',
 '0109066',
 '0075169',
 '0113542',
 '0110693',
 '0106544',
 '0116418',
 '0112607',
 '0120004',
 '0116654',
 '0116311',
 '0117965',
 '0114592',
 '0115725',
 '0115783',
 '0120271',
 '0113596',
 '0109001',
 '0094822',
 '0113253',
 '0117991',
 '0117093',
 '0024252',
 '1684935',
 '0111019',
 '0035896',
 '0032904',
 '0045152',
 '0043278',
 '0050419',
 '0054698',
 '0052357',
 '0047396',
 '0025316',
 '0036855',
 '0025164',
 '0053125',
 '0053604',
 '0053291',
 '0056923',
 '0034583',
 '0033870',
 '0058385',
 '0047437',
 '0046250',
 '0031580',
 '0037059',
 '0032138',
 '0031381',
 '0084370',
 '0043014',
 '0033467',
 '0062622',
 '0039428',
 '0042192',
 '0032143',
 '0032976',
 '0032484',
 '0038787',
 '0038109',
 '0050105',
 '0048728',
 '0042451',
 '0045537',
 '0031725',
 '0050658',
 '0051658',
 '0052126',
 '0029843',
 '0032762',
 '0037008',
 '0039420',
 '0029162',
 '0027125',
 '0035446',
 '0028010',
 '0049261',
 '0048028',
 '0025878',
 '0032599',
 '0048960',
 '0038650',
 '0031679',
 '0029947',
 '0034012',
 '0017350',
 '0036094',
 '0025586',
 '0038300',
 '0027893',
 '0032022',
 '0041509',
 '0039152',
 '0026029',
 '0038235',
 '0036241',
 '0063350',
 '0043265',
 '0046414',
 '0051459',
 '0047162',
 '0033891',
 '0029855',
 '0029588',
 '0022879',
 '0027980',
 '0114007',
 '0093229',
 '0118927',
 '0048491',
 '0113730',
 '0117357',
 '0117669',
 '0116329',
 '0118742',
 '0116442',
 '0114354',
 '0117011',
 '0117039',
 '0117473',
 '0116635',
 '0115678',
 '0116830',
 '0115847',
 '0117603',
 '0115438',
 '0115994',
 '0083587',
 '0116167',
 '0116259',
 '0116421',
 '0116000',
 '0115862',
 '0072653',
 '0047977',
 '0072951',
 '0064603',
 '0071607',
 '0050798',
 '0055277',
 '0054195',
 '0107131',
 '0053271',
 '0054357',
 '0059793',
 '0046672',
 '0106611',
 '0109127',
 '0042332',
 '0063819',
 '0038166',
 '0057546',
 '0041890',
 '0102798',
 '0058331',
 ...]

In [541]:
data['imdb_id'] = new_imdb

In [542]:
# Dropping imdb_ids that are not numeric
data = data[data.imdb_id.apply(lambda x: x.isnumeric())]

In [543]:
data

,adult,budget,genres,id,imdb_id,original_language,original_title,popularity,poster_path,release_date,revenue,runtime,status,title,video,vote_average,vote_count
0,False,30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,0114709,en,Toy Story,21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,1995-10-30,373554033.0,81.0,Released,Toy Story,False,7.7,5415.0
1,False,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,0113497,en,Jumanji,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,1995-12-15,262797249.0,104.0,Released,Jumanji,False,6.9,2413.0
2,False,0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,0113228,en,Grumpier Old Men,11.7129,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,1995-12-22,0.0,101.0,Released,Grumpier Old Men,False,6.5,92.0
3,False,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,0114885,en,Waiting to Exhale,3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,1995-12-22,81452156.0,127.0,Released,Waiting to Exhale,False,6.1,34.0
4,False,0,"[{'id': 35, 'name': 'Comedy'}]",11862,0113041,en,Father of the Bride Part II,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,1995-02-10,76578911.0,106.0,Released,Father of the Bride Part II,False,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,False,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",439050,6209470,fa,رگ خواب,0.072051,/jldsYflnId4tTWPx8es3uzsB1I8.jpg,NaN,0.0,90.0,Released,Subdue,False,4.0,1.0
45462,False,0,"[{'id': 18, 'name': 'Drama'}]",111109,2028550,tl,Siglo ng Pagluluwal,0.178241,/xZkmxsNmYXJbKVsTRLLx3pqGHx7.jpg,2011-11-17,0.0,360.0,Released,Century of Birthing,False,9.0,3.0
45463,False,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",67758,0303758,en,Betrayal,0.903007,/d5bX92nDsISNhu3ZT69uHwmfCGw.jpg,2003-08-01,0.0,90.0,Released,Betrayal,False,3.8,6.0
45464,False,0,[],227506,0008536,en,Satana likuyushchiy,0.003503,/aorBPO7ak8e8iJKT5OcqYxU3jlK.jpg,1917-10-21,0.0,87.0,Released,Satan Triumphant,False,0.0,0.0
45465,False,0,[],461257,6980792,en,Queerama,0.163015,/s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg,2017-06-09,0.0,75.0,Released,Queerama,False,0.0,0.0

In [544]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45443 entries, 0 to 45465
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   adult              45443 non-null  object
 1   budget             45443 non-null  object
 2   genres             45443 non-null  object
 3   id                 45443 non-null  object
 4   imdb_id            45443 non-null  object
 5   original_language  45432 non-null  object
 6   original_title     45443 non-null  object
 7   popularity         45443 non-null  object
 8   poster_path        45065 non-null  object
 9   release_date       45362 non-null  object
 10  revenue            45443 non-null  float64
 11  runtime            45188 non-null  float64
 12  status             45362 non-null  object
 13  title              45443 non-null  object
 14  video              45443 non-null  object
 15  vote_average       45443 non-null  float64
 16  vote_count         45443 non-null  float64
dtypes: float64(4), object(13)
memory usage: 6.2+ MB

In [545]:
data['id'].nunique()

45413

In [546]:
data['original_language'].nunique()

89

In [547]:
data['original_language'].value_counts()

en    32254
fr     2437
it     1529
ja     1348
de     1080
      ...
ay        1
rw        1
cy        1
tg        1
si        1
Name: original_language, Length: 89, dtype: int64

In [548]:
# Dropping duplicate movie id's for primary key constraint
data = data.drop_duplicates(subset='id', keep='first')

In [549]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45413 entries, 0 to 45465
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   adult              45413 non-null  object
 1   budget             45413 non-null  object
 2   genres             45413 non-null  object
 3   id                 45413 non-null  object
 4   imdb_id            45413 non-null  object
 5   original_language  45402 non-null  object
 6   original_title     45413 non-null  object
 7   popularity         45413 non-null  object
 8   poster_path        45035 non-null  object
 9   release_date       45332 non-null  object
 10  revenue            45413 non-null  float64
 11  runtime            45158 non-null  float64
 12  status             45332 non-null  object
 13  title              45413 non-null  object
 14  video              45413 non-null  object
 15  vote_average       45413 non-null  float64
 16  vote_count         45413 non-null  float64
dtypes: float64(4), object(13)
memory usage: 6.2+ MB

In [550]:
data.head()

,adult,budget,genres,id,imdb_id,original_language,original_title,popularity,poster_path,release_date,revenue,runtime,status,title,video,vote_average,vote_count
0,False,30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,0114709,en,Toy Story,21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,1995-10-30,373554033.0,81.0,Released,Toy Story,False,7.7,5415.0
1,False,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,0113497,en,Jumanji,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,1995-12-15,262797249.0,104.0,Released,Jumanji,False,6.9,2413.0
2,False,0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,0113228,en,Grumpier Old Men,11.7129,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,1995-12-22,0.0,101.0,Released,Grumpier Old Men,False,6.5,92.0
3,False,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,0114885,en,Waiting to Exhale,3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,1995-12-22,81452156.0,127.0,Released,Waiting to Exhale,False,6.1,34.0
4,False,0,"[{'id': 35, 'name': 'Comedy'}]",11862,0113041,en,Father of the Bride Part II,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,1995-02-10,76578911.0,106.0,Released,Father of the Bride Part II,False,5.7,173.0

In [551]:
# Regex to extract the names of the genres in JSON formatted data
data['list_genres'] = data['genres'].str.findall("(?:'name':\s)(\W[A-Z][a-z]*\W)(?:})")
data.head()

/Users/briannahancock/opt/anaconda3/envs/PythonData2/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,adult,budget,genres,id,imdb_id,original_language,original_title,popularity,poster_path,release_date,revenue,runtime,status,title,video,vote_average,vote_count,list_genres
0,False,30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,0114709,en,Toy Story,21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,1995-10-30,373554033.0,81.0,Released,Toy Story,False,7.7,5415.0,"['Animation', 'Comedy', 'Family']"
1,False,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,0113497,en,Jumanji,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,1995-12-15,262797249.0,104.0,Released,Jumanji,False,6.9,2413.0,"['Adventure', 'Fantasy', 'Family']"
2,False,0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,0113228,en,Grumpier Old Men,11.7129,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,1995-12-22,0.0,101.0,Released,Grumpier Old Men,False,6.5,92.0,"['Romance', 'Comedy']"
3,False,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,0114885,en,Waiting to Exhale,3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,1995-12-22,81452156.0,127.0,Released,Waiting to Exhale,False,6.1,34.0,"['Comedy', 'Drama', 'Romance']"
4,False,0,"[{'id': 35, 'name': 'Comedy'}]",11862,0113041,en,Father of the Bride Part II,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,1995-02-10,76578911.0,106.0,Released,Father of the Bride Part II,False,5.7,173.0,['Comedy']

In [552]:
# Replacing commas from csv for importing into postgres database
titles = data['title']
cleaned_titles = []
for title in titles:
    title = str(title)
    title = title.replace(',', ':')
    cleaned_titles.append(title)
cleaned_titles

['Toy Story',
 'Jumanji',
 'Grumpier Old Men',
 'Waiting to Exhale',
 'Father of the Bride Part II',
 'Heat',
 'Sabrina',
 'Tom and Huck',
 'Sudden Death',
 'GoldenEye',
 'The American President',
 'Dracula: Dead and Loving It',
 'Balto',
 'Nixon',
 'Cutthroat Island',
 'Casino',
 'Sense and Sensibility',
 'Four Rooms',
 'Ace Ventura: When Nature Calls',
 'Money Train',
 'Get Shorty',
 'Copycat',
 'Assassins',
 'Powder',
 'Leaving Las Vegas',
 'Othello',
 'Now and Then',
 'Persuasion',
 'The City of Lost Children',
 'Shanghai Triad',
 'Dangerous Minds',
 'Twelve Monkeys',
 'Wings of Courage',
 'Babe',
 'Carrington',
 'Dead Man Walking',
 'Across the Sea of Time',
 'It Takes Two',
 'Clueless',
 'Cry: the Beloved Country',
 'Richard III',
 'Dead Presidents',
 'Restoration',
 'Mortal Kombat',
 'To Die For',
 'How To Make An American Quilt',
 'Se7en',
 'Pocahontas',
 'When Night Is Falling',
 'The Usual Suspects',
 'Guardian Angel',
 'Mighty Aphrodite',
 'Lamerica',
 'The Big Green',
 'Georgia',
 'Kids of the Round Table',
 'Home for the Holidays',
 'The Postman',
 'The Confessional',
 'The Indian in the Cupboard',
 'Eye for an Eye',
 "Mr. Holland's Opus",
 "Don't Be a Menace to South Central While Drinking Your Juice in the Hood",
 'Two If by Sea',
 'Bio-Dome',
 'Lawnmower Man 2: Beyond Cyberspace',
 'Two Bits',
 'French Twist',
 'Friday',
 'From Dusk Till Dawn',
 'Fair Game',
 'Kicking and Screaming',
 'Les Miserables',
 'Bed of Roses',
 'Big Bully',
 'Screamers',
 'Nico Icon',
 'The Crossing Guard',
 'The Juror',
 'The White Balloon',
 "Things to Do in Denver When You're Dead",
 "Antonia's Line",
 'Once Upon a Time... When We Were Colored',
 'Last Summer in the Hamptons',
 'Angels and Insects',
 'White Squall',
 'Dunston Checks In',
 'Black Sheep',
 'Nick of Time',
 'The Journey of August King',
 'Mary Reilly',
 'Vampire in Brooklyn',
 'Beautiful Girls',
 'Broken Arrow',
 "A Midwinter's Tale",
 'La Haine',
 'Shopping',
 'Heidi Fleiss: Hollywood Madam',
 'City Hall',
 'Bottle Rocket',
 'Mr. Wrong',
 'Unforgettable',
 'Happy Gilmore',
 'The Bridges of Madison County',
 'Nobody Loves Me',
 'Muppet Treasure Island',
 'Catwalk',
 'Headless Body in Topless Bar',
 'Braveheart',
 'Taxi Driver',
 'Rumble in the Bronx',
 'Before and After',
 "Margaret's Museum",
 'Happiness Is in the Field',
 'Anne Frank Remembered',
 "The Young Poisoner's Handbook",
 'If Lucy Fell',
 'Steal Big Steal Little',
 'Race the Sun',
 'The Boys of St. Vincent',
 'Boomerang',
 'Chungking Express',
 'The Star Maker',
 'Flirting with Disaster',
 'The Neverending Story III: Escape from Fantasia',
 'The Silences of the Palace',
 "Jupiter's Wife",
 'Pie in the Sky',
 'Angela',
 'Frankie Starlight',
 'Jade',
 'Nueba Yol',
 'Sonic Outlaws',
 'Down Periscope',
 'From the Journals of Jean Seberg',
 'Man of the Year',
 'The Neon Bible',
 'Target',
 'Up Close & Personal',
 'The Birdcage',
 'Virgin Mary',
 'The Brothers McMullen',
 'Bad Boys',
 'The Amazing Panda Adventure',
 'The Basketball Diaries',
 'An Awfully Big Adventure',
 'Amateur',
 'Apollo 13',
 'Rob Roy',
 'The Addiction',
 'Batman Forever',
 'Belle de Jour',
 'Beyond Rangoon',
 'Blue in the Face',
 'Canadian Bacon',
 'Casper',
 'Clockers',
 'Congo',
 'Crimson Tide',
 'Crumb',
 'Desperado',
 'Devil in a Blue Dress',
 'Die Hard: With a Vengeance',
 'The Doom Generation',
 'Feast of July',
 'First Knight',
 'Free Willy 2 - The Adventure Home',
 'Hackers',
 'Jeffrey',
 'Johnny Mnemonic',
 'Judge Dredd',
 'Jury Duty',
 'Kids',
 'Living in Oblivion',
 'Lord of Illusions',
 'Love & Human Remains',
 'Mad Love',
 'Mallrats',
 'Mighty Morphin Power Rangers: The Movie',
 'Moonlight and Valentino',
 'Mute Witness',
 'Nadja',
 'The Net',
 'Nine Months',
 'Party Girl',
 'The Prophecy',
 'Reckless',
 'Safe',
 'The Scarlet Letter',
 'The Show',
 'Showgirls',
 'Smoke',
 'Something to Talk About',
 'Species',
 'The Stars Fell on Henrietta',
 'Strange Days',
 'The Umbrellas of Cherbourg',
 'The Tie That Binds',
 'Three Wishes',
 'Total Eclipse',
 'To Wong Foo: Thanks for Everything! Julie Newmar',
 'Under Siege 2: Dark Territory',
 'Unstrung Heroes',
 'Unzipped',
 'A Walk in the Clouds',
 'Waterworld',
 "White Man's Burden",
 'Wild Bill',
 'The Browning Version',
 'Bushwhacked',
 'Burnt by the Sun',
 'Before the Rain',
 'Before Sunrise',
 'Billy Madison',
 'The Babysitter',
 'Boys on the Side',
 'The Cure',
 'Castle Freak',
 'Circle of Friends',
 'Clerks',
 'Don Juan DeMarco',
 'Disclosure',
 'Dream Man',
 'Drop Zone',
 'Destiny Turns on the Radio',
 'Death and the Maiden',
 'Dolores Claiborne',
 'Dumb and Dumber',
 'Eat Drink Man Woman',
 'Exotica',
 'Exit to Eden',
 'Ed Wood',
 'French Kiss',
 'Forget Paris',
 'Far from Home: The Adventures of Yellow Dog',
 'A Goofy Movie',
 'Hideaway',
 'Fluke',
 'Farinelli',
 'Gordy',
 'Gumby: The Movie',
 'The Glass Shield',
 'Hoop Dreams',
 'Heavenly Creatures',
 'Houseguest',
 'Immortal Beloved',
 'Heavyweights',
 'The Hunted',
 'I.Q.',
 'Interview with the Vampire',
 'Jefferson in Paris',
 'The Jerky Boys',
 'Junior',
 'Just Cause',
 "A Kid in King Arthur's Court",
 'Kiss of Death',
 'Star Wars',
 'Little Women',
 'A Little Princess',
 'Ladybird Ladybird',
 "L'Enfer",
 'Like Water for Chocolate',
 'Legends of the Fall',
 'Major Payne',
 'Little Odessa',
 'Mi Vida Loca',
 'Love Affair',
 'Losing Isaiah',
 'The Madness of King George',
 "Mary Shelley's Frankenstein",
 'Man of the House',
 'Mixed Nuts',
 'Milk Money',
 'Miracle on 34th Street',
 'Miami Rhapsody',
 'My Family',
 'Murder in the First',
 "Nobody's Fool",
 'Nell',
 'New Jersey Drive',
 'New York Cop',
 'Beyond Bedlam',
 'Nemesis 2 - Nebula',
 'Nina Takes a Lover',
 'Natural Born Killers',
 'Only You',
 'Once Were Warriors',
 'Poison Ivy II: Lily',
 'Outbreak',
 'Leon: The Professional',
 'The Perez Family',
 "A Pyromaniac's Love Story",
 'Pulp Fiction',
 'Panther',
 'Pushing Hands',
 'Priest',
 'Quiz Show',
 'Picture Bride',
 'Queen Margot',
 'The Quick and the Dead',
 'Roommates',
 'Prêt-à-Porter',
 'Three Colors: Red',
 'Three Colors: Blue',
 'Three Colors: White',
 'Red Firecracker: Green Firecracker',
 'Rent-a-Kid',
 'Relative Fear',
 'Stuart Saves His Family',
 'The Swan Princess',
 'The Secret of Roan Inish',
 'The Specialist',
 'Stargate',
 'The Santa Clause',
 'The Shawshank Redemption',
 'Shallow Grave',
 'Suture',
 'Strawberry and Chocolate',
 'Swimming with Sharks',
 'The Sum of Us',
 'Senior Trip',
 'To Live',
 'Tank Girl',
 'Tales from the Crypt: Demon Knight',
 'Star Trek: Generations',
 'Tales from the Hood',
 'Tom & Viv',
 'Village of the Damned',
 'Tommy Boy',
 'Vanya on 42nd Street',
 'The Underneath',
 'The Walking Dead',
 "What's Eating Gilbert Grape",
 'Virtuosity',
 'While You Were Sleeping',
 'The War',
 'Double Happiness',
 "Muriel's Wedding",
 'The Baby-Sitters Club',
 'Ace Ventura: Pet Detective',
 'The Adventures of Priscilla: Queen of the Desert',
 'Backbeat',
 'Bitter Moon',
 'Bullets Over Broadway',
 'Clear and Present Danger',
 'The Client',
 'Corrina: Corrina',
 'Crooklyn',
 'The Crow',
 'Cobb',
 'The Flintstones',
 'Forrest Gump',
 'Four Weddings and a Funeral',
 'Higher Learning',
 'I Like It Like That',
 'I Love Trouble',
 'It Could Happen to You',
 'The Jungle Book',
 'The Wonderful: Horrible Life of Leni Riefenstahl',
 'The Lion King',
 'Little Buddha',
 'New Nightmare',
 'The Mask',
 'Maverick',
 'Mrs. Parker and the Vicious Circle',
 'The Naked Gun 33⅓: The Final Insult',
 'The Paper',
 'Reality Bites',
 'Red Rock West',
 'Ri¢hie Ri¢h',
 'Safe Passage',
 'The River Wild',
 'Speed',
 'Speechless',
 'Timecop',
 'True Lies',
 'When a Man Loves a Woman',
 'Wolf',
 'Wyatt Earp',
 'Bad Company',
 'A Man of No Importance',
 'S.F.W.',
 'A Low Down Dirty Shame',
 'Boys Life: Three Stories of Love: Lust: and Liberation',
 'Colonel Chabert',
 'Faster: Pussycat! Kill! Kill!',
 "Jason's Lyric",
 'The Secret Adventures of Tom Thumb',
 'Street Fighter',
 'Coldblooded',
 'Desert Winds',
 'Fall Time',
 'The Fear',
 'Frank and Ollie',
 'Girl in the Cadillac',
 'Homage',
 'Mirage',
 'Open Season',
 'Dos Crímenes',
 'Brother Minister: The Assassination of Malcolm X',
 'Highlander: The Final Dimension',
 'Federal Hill',
 'In the Mouth of Madness',
 '8 Seconds',
 'Above the Rim',
 'Addams Family Values',
 'Martin Lawrence: You So Crazy',
 'The Age of Innocence',
 'Airheads',
 'The Air Up There',
 'Another Stakeout',
 'Bad Girls',
 'Barcelona',
 'Being Human',
 'The Beverly Hillbillies',
 'Beverly Hills Cop III',
 'Black Beauty',
 'Blink',
 'Blown Away',
 'Blue Chips',
 'Blue Sky',
 'Body Snatchers',
 'Boxing Helena',
 'A Bronx Tale',
 'Cabin Boy',
 'Calendar Girl',
 "Carlito's Way",
 "City Slickers II: The Legend of Curly's Gold",
 'Clean Slate',
 'Cliffhanger',
 'Coneheads',
 'Color of Night',
 'Cops & Robbersons',
 'The Cowboy Way',
 'Dangerous Game',
 'Dave',
 'Dazed and Confused',
 'Demolition Man',
 'The Endless Summer 2',
 'Even Cowgirls Get the Blues',
 'Fatal Instinct',
 'Farewell My Concubine',
 'The Favor',
 'Fearless',
 'Fear of a Black Hat',
 'With Honors',
 'Flesh and Bone',
 "Widows' Peak",
 'For Love or Money',
 'The Firm',
 'Free Willy',
 'Fresh',
 'The Fugitive',
 'Geronimo: An American Legend',
 'The Getaway',
 'Getting Even with Dad',
 'Go Fish',
 'A Good Man in Africa',
 'Guilty as Sin',
 'Hard Target',
 'Heaven & Earth',
 'Hot Shots! Part Deux',
 'Live Nude Girls',
 'The Englishman Who Went Up a Hill But Came Down a Mountain',
 'The House of the Spirits',
 'House Party 3',
 'The Hudsucker Proxy',
 "I'll Do Anything",
 'In the Army Now',
 'In the Line of Fire',
 'In the Name of the Father',
 'The Inkwell',
 "What's Love Got to Do with It",
 'Jimmy Hollywood',
 'Judgment Night',
 'Jurassic Park',
 'Kalifornia',
 'Killing Zoe',
 'King of the Hill',
 'Lassie',
 'Last Action Hero',
 'Life With Mikey',
 'Lightning Jack',
 'M. Butterfly',
 'Made in America',
 'Malice',
 'The Man without a Face',
 'Manhattan Murder Mystery',
 'Menace II Society',
 'Executive Decision',
 'In the Realm of the Senses',
 'What Happened Was...',
 'Much Ado About Nothing',
 'Mr. Jones',
 'Mr. Wonderful',
 'Mrs. Doubtfire',
 'Naked',
 'The Next Karate Kid',
 'The New Age',
 'No Escape',
 'North',
 'Orlando',
 'A Perfect World',
 'Philadelphia',
 'The Piano',
 'Poetic Justice',
 'The Program',
 'The Puppet Masters',
 'Radioland Murders',
 'The Ref',
 'The Remains of the Day',
 'Renaissance Man',
 'Rising Sun',
 'The Road to Wellville',
 'RoboCop 3',
 'Robin Hood: Men in Tights',
 'Romeo Is Bleeding',
 'Romper Stomper',
 'Ruby in Paradise',
 'Rudy',
 'The Saint of Fort Washington',
 'Savage Nights',
 "Schindler's List",
 'The Scout',
 'Searching for Bobby Fischer',
 'Second Best',
 'The Secret Garden',
 'Serial Mom',
 'The Shadow',
 'Shadowlands',
 'Short Cuts',
 'A Simple Twist of Fate',
 'Sirens',
 'Six Degrees of Separation',
 'Sleepless in Seattle',
 'Sliver',
 'Blade Runner',
 'Son in Law',
 'So I Married an Axe Murderer',
 'Striking Distance',
 'Harem',
 'Super Mario Bros.',
 'Surviving the Game',
 'Terminal Velocity',
 'Thirty Two Short Films About Glenn Gould',
 'Threesome',
 'The Nightmare Before Christmas',
 'The Three Musketeers',
 'Tombstone',
 'Trial by Jury',
 'True Romance',
 'The War Room',
 'The Pagemaster',
 'Paris: France',
 'The Beans of Egypt: Maine',
 'Killer',
 'Welcome to the Dollhouse',
 'Germinal',
 'Chasers',
 'Cronos',
 'Naked in New York',
 'Kika',
 'Bhaji on the Beach',
 'Little Big League',
 'The Slingshot',
 'Wide Eyed and Legless',
 'Foreign Student',
 'Ciao: Professore!',
 'Spanking the Monkey',
 'The Little Rascals',
 'À la mode',
 'Andre',
 'The Escort',
 'Princess Caraboo',
 'The Celluloid Closet',
 'Café au Lait',
 'Dear Diary',
 "I Don't Want to Talk About It",
 'The Brady Bunch Movie',
 'Home Alone',
 'Ghost',
 'Aladdin',
 'Terminator 2: Judgment Day',
 'Dances with Wolves',
 'Tough and Deadly',
 'Batman',
 'The Silence of the Lambs',
 'Snow White and the Seven Dwarfs',
 'Beauty and the Beast',
 'Pinocchio',
 'Pretty Woman',
 'Window to Paris',
 'The Wild Bunch',
 'Love and a .45',
 "The Wooden Man's Bride",
 'A Great Day in Harlem',
 'Bye Bye Love',
 'One Fine Day',
 'Candyman: Farewell to the Flesh',
 'Century',
 'Fargo',
 'Homeward Bound II: Lost in San Francisco',
 'Heavy Metal',
 'Hellraiser: Bloodline',
 'The Pallbearer',
 'Jane Eyre',
 'Loaded',
 'Bread and Chocolate',
 'The Aristocats',
 'The Flower of My Secret',
 'Two Much',
 'Ed',
 'Scream of Stone',
 'My Favorite Season',
 'A Modern Affair',
 'Condition Red',
 'Halfaouine: Boy of the Terraces',
 'A Thin Line Between Love and Hate',
 'The Last Supper',
 'Primal Fear',
 'Rude',
 'Carried Away',
 'All Dogs Go to Heaven 2',
 'Land and Freedom',
 'Denise Calls Up',
 'Theodore Rex',
 'A Family Thing',
 'Frisk',
 'Sgt. Bilko',
 'Jack & Sarah',
 'Girl 6',
 'Diabolique',
 'Little Indian: Big City',
 'Roula',
 'Peanuts – Die Bank zahlt alles',
 'Happy Weekend',
 'Nelly and Monsieur Arnaud',
 'Courage Under Fire',
 'Mission: Impossible',
 'Cold Fever',
 'Moll Flanders',
 'The Superwife',
 '301: 302',
 'DragonHeart',
 'Und keiner weint mir nach',
 "My Mother's Courage",
 'Eddie',
 'Yankee Zulu',
 "Billy's Holiday",
 'Purple Noon',
 'August',
 'James and the Giant Peach',
 'Fear',
 'Kids in the Hall: Brain Candy',
 'Faithful',
 'Underground',
 'All Things Fair',
 'Bloodsport II',
 'Pather Panchali',
 'The World of Apu',
 'Mystery Science Theater 3000: The Movie',
 'Tarantella',
 'Space Jam',
 'Barbarella',
 'Hostile Intentions',
 'They Bite',
 'Some Folks Call It a Sling Blade',
 'The Run of the Country',
 'Alphaville',
 'Coup de Torchon',
 'Tigrero: A Film That Was Never Made',
 'The Eye of Vichy',
 'Windows',
 "It's My Party",
 'Country Life',
 'Operation Dumbo Drop',
 'The Promise',
 'Mrs. Winterbourne',
 'Solo',
 'Under The Domim Tree',
 'The Substitute',
 'True Crime',
 'Butterfly Kiss',
 'Feeling Minnesota',
 'Delta of Venus',
 'To Cross the Rubicon',
 'Angus',
 'Priest Daens',
 'Faces',
 'Boys',
 'The Quest',
 'Cosi',
 'Sunset Park',
 'Mulholland Falls',
 'The Truth About Cats & Dogs',
 'Oliver & Company',
 'Celtic Pride',
 'Flipper',
 'Captives',
 'Of Love and Shadows',
 'Dead Man',
 'The Horseman on the Roof',
 'Switchblade Sisters',
 'Mouth to Mouth',
 'The Visitors',
 'Multiplicity',
 'The Haunted World of Edward D. Wood: Jr.',
 'Two Friends',
 'The Craft',
 'The Great White Hype',
 'Last Dance',
 'War Stories Our Mother Never Told Us',
 'Cold Comfort Farm',
 'Institute Benjamenta: or This Dream People Call Human Life',
 "Heaven's Prisoners",
 'Original Gangstas',
 'The Rock',
 'Getting Away with Murder',
 'Cemetery Man',
 'Twister',
 'Barb Wire',
 'Le Garçu',
 'Honeymoon',
 'Ghost in the Shell',
 'Thinner',
 'Spy Hard',
 'Brothers in Trouble',
 'A Close Shave',
 'Force of Evil',
 'The Stupids',
 'The Arrival',
 'The Man from Down Under',
 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
 'Careful',
 'Vermont Is for Lovers',
 'A Month by the Lake',
 'Gold Diggers: The Secret of Bear Mountain',
 'Kim',
 'Carmen Miranda: Bananas Is My Business',
 'Ashes of Time',
 'The Jar',
 'Maya Lin: A Strong Clear Vision',
 'Stalingrad',
 'The Phantom',
 'Striptease',
 'The Last of the High Kings',
 'Heavy',
 'Jack',
 'I Shot Andy Warhol',
 'The Grass Harp',
 "Someone Else's America",
 'Life is Rosy',
 'Quartier Mozart',
 'Touki Bouki',
 "God's Gift",
 'Spirits of the Dead',
 'Babyfever',
 "Pharaoh's  Army",
 'Trainspotting',
 'Til There Was You',
 'Independence Day',
 'Stealing Beauty',
 'The Fan',
 'The Hunchback of Notre Dame',
 'The Cable Guy',
 'Kingpin',
 'Eraser',
 'The Gate of Heavenly Peace',
 'The Nutty Professor',
 'I: the Worst of All',
 'An Unforgettable Summer',
 'A Hungarian Fairy Tale',
 'My Life and Times With Antonin Artaud',
 'Midnight Dancers',
 'Somebody to Love',
 'A Very Natural Thing',
 'The Old Lady Who Walked in the Sea',
 'Daylight',
 'The Frighteners',
 'Lone Star',
 'Harriet the Spy',
 'Phenomenon',
 'Walking and Talking',
 "She's the One",
 'A Time to Kill',
 'American Buffalo',
 'Rendezvous in Paris',
 'Alaska',
 'Fled',
 'Kazaam',
 'Magic Hunter',
 'Larger Than Life',
 'A Boy Called Hate',
 'Power 98',
 'Two Deaths',
 'A Very Brady Sequel',
 'Stefano Quantestorie',
 'Death in the Garden',
 'Hedd Wyn',
 'La Collectionneuse',
 'Kaspar Hauser',
 'Regular Guys',
 'Diebinnen',
 'The Convent',
 'The Adventures of Pinocchio',
 "Joe's Apartment",
 'The First Wives Club',
 'Stonewall',
 'Ransom',
 'High School High',
 'Phat Beach',
 'Foxfire',
 'Chain Reaction',
 'Matilda',
 'Emma',
 'The Crow: City of Angels',
 'House Arrest',
 'Eyes Without a Face',
 'Bordello of Blood',
 'Lotto Land',
 'The Story of Xinghua',
 'The Day the Sun Turned Cold',
 'Flirt',
 'The Big Squeeze',
 'The Spitfire Grill',
 'Escape from L.A.',
 'Cyclo',
 'Basquiat',
 'Tin Cup',
 'Dingo',
 'The Ballad of Narayama',
 'Every Other Weekend',
 'Mille bolle blu',
 'Crows and Sparrows',
 'The Godfather',
 'Maybe... Maybe Not',
 'Police Story 3: Supercop',
 'Manny & Lo',
 'Wife',
 'Small Faces',
 'Bound',
 'Carpool',
 'Death in Brunswick',
 'Kansas City',
 "Gone Fishin'",
 "Lover's Knot",
 "Vive L'Amour",
 'Shadow of Angels',
 'Killer: A Journal of Murder',
 'Nothing to Lose',
 'Project S',
 'Girls Town',
 'Bye-Bye',
 'The Relic',
 'The Island of Dr. Moreau',
 'First Kid',
 'The Trigger Effect',
 'Sweet Nothing',
 'Bogus',
 'Bulletproof',
 'Talk of Angels',
 'The Land Before Time III: The Time of the Great Giving',
 '1-900',
 'Baton Rouge',
 'Halloween: The Curse of Michael Myers',
 'Twelfth Night',
 'Mother Night',
 'Liebelei',
 'Venice',
 'Wild Reeds',
 'For Whom the Bell Tolls',
 'The Philadelphia Story',
 "Singin' in the Rain",
 'An American in Paris',
 'Funny Face',
 "Breakfast at Tiffany's",
 'Vertigo',
 'Rear Window',
 'It Happened One Night',
 'Gaslight',
 'The Gay Divorcee',
 'North by Northwest',
 'The Apartment',
 'Some Like It Hot',
 'Charade',
 'Casablanca',
 'The Maltese Falcon',
 'My Fair Lady',
 'Sabrina',
 'Roman Holiday',
 'The Little Princess',
 'Meet Me in St. Louis',
 'The Wizard of Oz',
 'Gone with the Wind',
 'My Favorite Year',
 'Sunset Boulevard',
 'Citizen Kane',
 '2001: A Space Odyssey',
 'Golden Earrings',
 'All About Eve',
 'The Women',
 'Rebecca',
 'Foreign Correspondent',
 'Notorious',
 'Spellbound',
 'An Affair to Remember',
 'To Catch a Thief',
 'Father of the Bride',
 'The Band Wagon',
 'Ninotchka',
 'Love in the Afternoon',
 'Gigi',
 'The Reluctant Debutante',
 'The Adventures of Robin Hood',
 'The Mark of Zorro',
 'Laura',
 'The Ghost and Mrs. Muir',
 'Lost Horizon',
 'Top Hat',
 'To Be or Not to Be',
 'My Man Godfrey',
 'Giant',
 'East of Eden',
 'The Thin Man',
 'His Girl Friday',
 'Around the World in Eighty Days',
 "It's a Wonderful Life",
 'Mr. Smith Goes to Washington',
 'Bringing Up Baby',
 'Penny Serenade',
 'The Scarlet Letter',
 'Lady of Burlesque',
 'Of Human Bondage',
 'Angel on My Shoulder',
 'Little Lord Fauntleroy',
 'They Made Me a Criminal',
 'The Inspector General',
 'Angel and the Badman',
 'The 39 Steps',
 'A Walk in the Sun',
 'The Outlaw',
 'Night of the Living Dead',
 'The African Queen',
 'Beat the Devil',
 'Cat on a Hot Tin Roof',
 'The Last Time I Saw Paris',
 'Meet John Doe',
 'Algiers',
 'Something to Sing About',
 'A Farewell to Arms',
 'Moonlight Murder',
 'Nothing Personal',
 'Yes: Madam',
 'Dangerous Ground',
 'Picnic',
 'Madagascar Skin',
 'The Pompatus of Love',
 'Small Wonders',
 'Fly Away Home',
 'Bliss',
 'Grace of My Heart',
 'Brother of Sleep',
 'Maximum Risk',
 'Michael Collins',
 "The Rich Man's Wife",
 'Infinity',
 'Big Night',
 'Last Man Standing',
 'Caught',
 'Set It Off',
 '2 Days in the Valley',
 'Curdled',
 "L'associé",
 "Ed's Next Move",
 'Extreme Measures',
 'The Glimmer Man',
 'D3: The Mighty Ducks',
 'The Chamber',
 'The Apple Dumpling Gang',
 'Davy Crockett: King of the Wild Frontier',
 'Escape to Witch Mountain',
 'The Love Bug',
 'Herbie Rides Again',
 'Old Yeller',
 'The Parent Trap',
 'Pollyanna',

In [553]:
data['title'] = cleaned_titles

/Users/briannahancock/opt/anaconda3/envs/PythonData2/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [554]:
data.head()

,adult,budget,genres,id,imdb_id,original_language,original_title,popularity,poster_path,release_date,revenue,runtime,status,title,video,vote_average,vote_count,list_genres
0,False,30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,0114709,en,Toy Story,21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,1995-10-30,373554033.0,81.0,Released,Toy Story,False,7.7,5415.0,"['Animation', 'Comedy', 'Family']"
1,False,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,0113497,en,Jumanji,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,1995-12-15,262797249.0,104.0,Released,Jumanji,False,6.9,2413.0,"['Adventure', 'Fantasy', 'Family']"
2,False,0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,0113228,en,Grumpier Old Men,11.7129,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,1995-12-22,0.0,101.0,Released,Grumpier Old Men,False,6.5,92.0,"['Romance', 'Comedy']"
3,False,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,0114885,en,Waiting to Exhale,3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,1995-12-22,81452156.0,127.0,Released,Waiting to Exhale,False,6.1,34.0,"['Comedy', 'Drama', 'Romance']"
4,False,0,"[{'id': 35, 'name': 'Comedy'}]",11862,0113041,en,Father of the Bride Part II,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,1995-02-10,76578911.0,106.0,Released,Father of the Bride Part II,False,5.7,173.0,['Comedy']

In [555]:
# creating list of all genres to encode
from ast import literal_eval
ind, value = zip(*[(i, x) 
                  for i, row in data['genres'].items() 
                  for x in literal_eval(row)])
genre_col = pd.DataFrame(value, index=ind)
genre_col

          id       name
0         16  Animation
0         35     Comedy
0      10751     Family
1         12  Adventure
1         14    Fantasy
...      ...        ...
45461  10751     Family
45462     18      Drama
45463     28     Action
45463     18      Drama
45463     53   Thriller

[90976 rows x 2 columns]

In [556]:
# Dropping replaced columns
data = data.drop(columns=['genres', 'list_genres', 'original_title'])
data.head()

,adult,budget,id,imdb_id,original_language,popularity,poster_path,release_date,revenue,runtime,status,title,video,vote_average,vote_count
0,False,30000000,862,0114709,en,21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,1995-10-30,373554033.0,81.0,Released,Toy Story,False,7.7,5415.0
1,False,65000000,8844,0113497,en,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,1995-12-15,262797249.0,104.0,Released,Jumanji,False,6.9,2413.0
2,False,0,15602,0113228,en,11.7129,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,1995-12-22,0.0,101.0,Released,Grumpier Old Men,False,6.5,92.0
3,False,16000000,31357,0114885,en,3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,1995-12-22,81452156.0,127.0,Released,Waiting to Exhale,False,6.1,34.0
4,False,0,11862,0113041,en,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,1995-02-10,76578911.0,106.0,Released,Father of the Bride Part II,False,5.7,173.0

In [557]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45413 entries, 0 to 45465
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   adult              45413 non-null  object
 1   budget             45413 non-null  object
 2   id                 45413 non-null  object
 3   imdb_id            45413 non-null  object
 4   original_language  45402 non-null  object
 5   popularity         45413 non-null  object
 6   poster_path        45035 non-null  object
 7   release_date       45332 non-null  object
 8   revenue            45413 non-null  float64
 9   runtime            45158 non-null  float64
 10  status             45332 non-null  object
 11  title              45413 non-null  object
 12  video              45413 non-null  object
 13  vote_average       45413 non-null  float64
 14  vote_count         45413 non-null  float64
dtypes: float64(4), object(11)
memory usage: 5.5+ MB

In [558]:
data.to_csv('<file path>/<file name>.csv')

In [559]:
# Renaming columns for encoding
genre_col = genre_col.rename(columns={'name':'genre'})
genre_col

          id      genre
0         16  Animation
0         35     Comedy
0      10751     Family
1         12  Adventure
1         14    Fantasy
...      ...        ...
45461  10751     Family
45462     18      Drama
45463     28     Action
45463     18      Drama
45463     53   Thriller

[90976 rows x 2 columns]

In [560]:
genre_col['genre'].value_counts()

Drama              20239
Comedy             13173
Thriller            7616
Romance             6728
Action              6587
Horror              4670
Crime               4303
Documentary         3929
Adventure           3487
Science Fiction     3041
Family              2767
Mystery             2463
Fantasy             2307
Animation           1927
Foreign             1617
Music               1597
History             1397
War                 1322
Western             1041
TV Movie             765
Name: genre, dtype: int64

In [561]:
# Dropping genres that contain publisher info in genres column
genre_col['count'] = genre_col.groupby('genre').transform('count')
genre_counts = genre_col.loc[genre_col['count'] >= 2].drop(columns='count')

In [562]:
genre_counts['genre'].value_counts()

Drama              20239
Comedy             13173
Thriller            7616
Romance             6728
Action              6587
Horror              4670
Crime               4303
Documentary         3929
Adventure           3487
Science Fiction     3041
Family              2767
Mystery             2463
Fantasy             2307
Animation           1927
Foreign             1617
Music               1597
History             1397
War                 1322
Western             1041
TV Movie             765
Name: genre, dtype: int64

In [563]:
genre_counts

          id      genre
0         16  Animation
0         35     Comedy
0      10751     Family
1         12  Adventure
1         14    Fantasy
...      ...        ...
45461  10751     Family
45462     18      Drama
45463     28     Action
45463     18      Drama
45463     53   Thriller

[90976 rows x 2 columns]

In [564]:
# Create list of all columns to be encoded
genre_encoding_list = genre_counts.dtypes[genre_counts.dtypes == "object"].index.tolist()
genre_encoding_list

['genre']

In [565]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encoded_genres = pd.DataFrame(enc.fit_transform(genre_counts[genre_encoding_list]), index=genre_counts.index)

# Add the encoded variable names to the dataframe
encoded_genres.columns = enc.get_feature_names_out(genre_encoding_list)
encoded_genres.head()

,genre_Action,genre_Adventure,genre_Animation,genre_Comedy,genre_Crime,genre_Documentary,genre_Drama,genre_Family,genre_Fantasy,genre_Foreign,genre_History,genre_Horror,genre_Music,genre_Mystery,genre_Romance,genre_Science Fiction,genre_TV Movie,genre_Thriller,genre_War,genre_Western
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [582]:
encoded_genres.isna().sum()

genre_action             0
genre_adventure          0
genre_animation          0
genre_comedy             0
genre_crime              0
genre_documentary        0
genre_drama              0
genre_family             0
genre_fantasy            0
genre_foreign            0
genre_history            0
genre_horror             0
genre_music              0
genre_mystery            0
genre_romance            0
genre_science fiction    0
genre_tv movie           0
genre_thriller           0
genre_war                0
genre_western            0
dtype: int64

In [566]:
encoded_genres.columns

Index(['genre_Action', 'genre_Adventure', 'genre_Animation', 'genre_Comedy',
       'genre_Crime', 'genre_Documentary', 'genre_Drama', 'genre_Family',
       'genre_Fantasy', 'genre_Foreign', 'genre_History', 'genre_Horror',
       'genre_Music', 'genre_Mystery', 'genre_Romance',
       'genre_Science Fiction', 'genre_TV Movie', 'genre_Thriller',
       'genre_War', 'genre_Western'],
      dtype='object')

In [567]:
# Summing columns to group duplicated indexes
encoded_genres = encoded_genres.groupby(encoded_genres.index)['genre_Action', 'genre_Adventure', 'genre_Animation', 'genre_Comedy',
       'genre_Crime', 'genre_Documentary', 'genre_Drama', 'genre_Family',
       'genre_Fantasy', 'genre_Foreign', 'genre_History', 'genre_Horror',
       'genre_Music', 'genre_Mystery', 'genre_Romance',
       'genre_Science Fiction', 'genre_TV Movie', 'genre_Thriller',
       'genre_War', 'genre_Western'].apply(lambda x : x.astype(int).sum())

/Users/briannahancock/opt/anaconda3/envs/PythonData2/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.

In [568]:
encoded_genres.head()

,genre_Action,genre_Adventure,genre_Animation,genre_Comedy,genre_Crime,genre_Documentary,genre_Drama,genre_Family,genre_Fantasy,genre_Foreign,genre_History,genre_Horror,genre_Music,genre_Mystery,genre_Romance,genre_Science Fiction,genre_TV Movie,genre_Thriller,genre_War,genre_Western
0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
3,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0
4,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [569]:
# Column names to lower for SQL
encoded_genres.columns = encoded_genres.columns.str.lower()

In [570]:
encoded_genres.head()

,genre_action,genre_adventure,genre_animation,genre_comedy,genre_crime,genre_documentary,genre_drama,genre_family,genre_fantasy,genre_foreign,genre_history,genre_horror,genre_music,genre_mystery,genre_romance,genre_science fiction,genre_tv movie,genre_thriller,genre_war,genre_western
0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
3,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0
4,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [583]:
encoded_genres.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 42976 entries, 0 to 45463
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   genre_action           42976 non-null  int64
 1   genre_adventure        42976 non-null  int64
 2   genre_animation        42976 non-null  int64
 3   genre_comedy           42976 non-null  int64
 4   genre_crime            42976 non-null  int64
 5   genre_documentary      42976 non-null  int64
 6   genre_drama            42976 non-null  int64
 7   genre_family           42976 non-null  int64
 8   genre_fantasy          42976 non-null  int64
 9   genre_foreign          42976 non-null  int64
 10  genre_history          42976 non-null  int64
 11  genre_horror           42976 non-null  int64
 12  genre_music            42976 non-null  int64
 13  genre_mystery          42976 non-null  int64
 14  genre_romance          42976 non-null  int64
 15  genre_science fiction  42976 non-null  int64
 16  genre_tv movie         42976 non-null  int64
 17  genre_thriller         42976 non-null  int64
 18  genre_war              42976 non-null  int64
 19  genre_western          42976 non-null  int64
dtypes: int64(20)
memory usage: 6.9 MB

In [571]:
encoded_genres.to_csv('<file path>/<file name>.csv')

In [572]:
movies = pd.read_csv('<file path>/<file name>.csv', index_col='movieId')
movies.head()

,title,genres
movieId,,
1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
2,Jumanji (1995),Adventure|Children|Fantasy
3,Grumpier Old Men (1995),Comedy|Romance
4,Waiting to Exhale (1995),Comedy|Drama|Romance
5,Father of the Bride Part II (1995),Comedy

In [573]:
# Replacing commas for SQL database
movie_titles = movies['title']
cleaned_movies = []
for movie in movie_titles:
    movie = str(movie)
    movie = movie.replace(',', ';')
    cleaned_movies.append(movie)
cleaned_movies

['Toy Story (1995)',
 'Jumanji (1995)',
 'Grumpier Old Men (1995)',
 'Waiting to Exhale (1995)',
 'Father of the Bride Part II (1995)',
 'Heat (1995)',
 'Sabrina (1995)',
 'Tom and Huck (1995)',
 'Sudden Death (1995)',
 'GoldenEye (1995)',
 'American President; The (1995)',
 'Dracula: Dead and Loving It (1995)',
 'Balto (1995)',
 'Nixon (1995)',
 'Cutthroat Island (1995)',
 'Casino (1995)',
 'Sense and Sensibility (1995)',
 'Four Rooms (1995)',
 'Ace Ventura: When Nature Calls (1995)',
 'Money Train (1995)',
 'Get Shorty (1995)',
 'Copycat (1995)',
 'Assassins (1995)',
 'Powder (1995)',
 'Leaving Las Vegas (1995)',
 'Othello (1995)',
 'Now and Then (1995)',
 'Persuasion (1995)',
 'City of Lost Children; The (Cité des enfants perdus; La) (1995)',
 'Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)',
 'Dangerous Minds (1995)',
 'Twelve Monkeys (a.k.a. 12 Monkeys) (1995)',
 'Wings of Courage (1995)',
 'Babe (1995)',
 'Carrington (1995)',
 'Dead Man Walking (1995)',
 'Across the Sea of Time (1995)',
 'It Takes Two (1995)',
 'Clueless (1995)',
 'Cry; the Beloved Country (1995)',
 'Richard III (1995)',
 'Dead Presidents (1995)',
 'Restoration (1995)',
 'Mortal Kombat (1995)',
 'To Die For (1995)',
 'How to Make an American Quilt (1995)',
 'Seven (a.k.a. Se7en) (1995)',
 'Pocahontas (1995)',
 'When Night Is Falling (1995)',
 'Usual Suspects; The (1995)',
 'Guardian Angel (1994)',
 'Mighty Aphrodite (1995)',
 'Lamerica (1994)',
 'Big Green; The (1995)',
 'Georgia (1995)',
 'Kids of the Round Table (1995)',
 'Home for the Holidays (1995)',
 'Postman; The (Postino; Il) (1994)',
 'Confessional; The (Confessionnal; Le) (1995)',
 'Indian in the Cupboard; The (1995)',
 'Eye for an Eye (1996)',
 "Mr. Holland's Opus (1995)",
 "Don't Be a Menace to South Central While Drinking Your Juice in the Hood (1996)",
 'Two if by Sea (1996)',
 'Bio-Dome (1996)',
 'Lawnmower Man 2: Beyond Cyberspace (1996)',
 'Two Bits (1995)',
 'French Twist (Gazon maudit) (1995)',
 'Friday (1995)',
 'From Dusk Till Dawn (1996)',
 'Fair Game (1995)',
 'Kicking and Screaming (1995)',
 'Misérables; Les (1995)',
 'Bed of Roses (1996)',
 'Big Bully (1996)',
 'Screamers (1995)',
 'Nico Icon (1995)',
 'Crossing Guard; The (1995)',
 'Juror; The (1996)',
 'White Balloon; The (Badkonake sefid) (1995)',
 "Things to Do in Denver When You're Dead (1995)",
 "Antonia's Line (Antonia) (1995)",
 'Once Upon a Time... When We Were Colored (1995)',
 'Last Summer in the Hamptons (1995)',
 'Angels and Insects (1995)',
 'White Squall (1996)',
 'Dunston Checks In (1996)',
 'Black Sheep (1996)',
 'Nick of Time (1995)',
 'The Journey of August King (1995)',
 'Mary Reilly (1996)',
 'Vampire in Brooklyn (1995)',
 'Beautiful Girls (1996)',
 'Broken Arrow (1996)',
 'In the Bleak Midwinter (1995)',
 'Hate (Haine; La) (1995)',
 'Shopping (1994)',
 'Heidi Fleiss: Hollywood Madam (1995)',
 'City Hall (1996)',
 'Bottle Rocket (1996)',
 'Mr. Wrong (1996)',
 'Unforgettable (1996)',
 'Happy Gilmore (1996)',
 'Bridges of Madison County; The (1995)',
 'Nobody Loves Me (Keiner liebt mich) (1994)',
 'Muppet Treasure Island (1996)',
 'Catwalk (1996)',
 'Headless Body in Topless Bar (1995)',
 'Braveheart (1995)',
 'Taxi Driver (1976)',
 'Rumble in the Bronx (Hont faan kui) (1995)',
 'Before and After (1996)',
 "Margaret's Museum (1995)",
 'Happiness Is in the Field (Bonheur est dans le pré; Le) (1995)',
 'Anne Frank Remembered (1995)',
 "Young Poisoner's Handbook; The (1995)",
 'If Lucy Fell (1996)',
 'Steal Big; Steal Little (1995)',
 'Race the Sun (1996)',
 'Boys of St. Vincent; The (1992)',
 'Boomerang (1992)',
 'Chungking Express (Chung Hing sam lam) (1994)',
 "Star Maker; The (Uomo delle stelle; L') (1995)",
 'Flirting With Disaster (1996)',
 'NeverEnding Story III; The (1994)',
 'Silences of the Palace; The (Saimt el Qusur) (1994)',
 "Jupiter's Wife (1994)",
 'Pie in the Sky (1996)',
 'Angela (1995)',
 'Frankie Starlight (1995)',
 'Jade (1995)',
 'Nueba Yol (1995)',
 'Sonic Outlaws (1995)',
 'Down Periscope (1996)',
 'From the Journals of Jean Seberg (1995)',
 'Man of the Year (1995)',
 'Neon Bible; The (1995)',
 'Target (1995)',
 'Up Close and Personal (1996)',
 'Birdcage; The (1996)',
 'Shadows (Cienie) (1988)',
 'Gospa (1995)',
 'Brothers McMullen; The (1995)',
 'Bad Boys (1995)',
 'Amazing Panda Adventure; The (1995)',
 'Basketball Diaries; The (1995)',
 'Awfully Big Adventure; An (1995)',
 'Amateur (1994)',
 'Apollo 13 (1995)',
 'Rob Roy (1995)',
 'Addiction; The (1995)',
 'Batman Forever (1995)',
 'Beauty of the Day (Belle de jour) (1967)',
 'Beyond Rangoon (1995)',
 'Blue in the Face (1995)',
 'Canadian Bacon (1995)',
 'Casper (1995)',
 'Clockers (1995)',
 'Congo (1995)',
 'Crimson Tide (1995)',
 'Crumb (1994)',
 'Desperado (1995)',
 'Devil in a Blue Dress (1995)',
 'Die Hard: With a Vengeance (1995)',
 'Doom Generation; The (1995)',
 'Feast of July (1995)',
 'First Knight (1995)',
 'Free Willy 2: The Adventure Home (1995)',
 'Hackers (1995)',
 'Jeffrey (1995)',
 'Johnny Mnemonic (1995)',
 'Judge Dredd (1995)',
 'Jury Duty (1995)',
 'Kids (1995)',
 'Living in Oblivion (1995)',
 'Lord of Illusions (1995)',
 'Love & Human Remains (1993)',
 'Mad Love (1995)',
 'Mallrats (1995)',
 'Mighty Morphin Power Rangers: The Movie (1995)',
 'Moonlight and Valentino (1995)',
 'Mute Witness (1994)',
 'Nadja (1994)',
 'Net; The (1995)',
 'Nine Months (1995)',
 'Party Girl (1995)',
 'Prophecy; The (1995)',
 'Reckless (1995)',
 'Safe (1995)',
 'Scarlet Letter; The (1995)',
 'The Show (1995)',
 'Showgirls (1995)',
 'Smoke (1995)',
 'Something to Talk About (1995)',
 'Species (1995)',
 'Stars Fell on Henrietta; The (1995)',
 'Strange Days (1995)',
 'Umbrellas of Cherbourg; The (Parapluies de Cherbourg; Les) (1964)',
 'Tie That Binds; The (1995)',
 'Three Wishes (1995)',
 'Total Eclipse (1995)',
 'To Wong Foo; Thanks for Everything! Julie Newmar (1995)',
 'Under Siege 2: Dark Territory (1995)',
 'Unstrung Heroes (1995)',
 'Unzipped (1995)',
 'Walk in the Clouds; A (1995)',
 'Waterworld (1995)',
 "White Man's Burden (1995)",
 'Wild Bill (1995)',
 'Browning Version; The (1994)',
 'Bushwhacked (1995)',
 'Burnt by the Sun (Utomlyonnye solntsem) (1994)',
 'Before the Rain (Pred dozhdot) (1994)',
 'Before Sunrise (1995)',
 'Billy Madison (1995)',
 'Babysitter; The (1995)',
 'Boys on the Side (1995)',
 'Cure; The (1995)',
 'Castle Freak (1995)',
 'Circle of Friends (1995)',
 'Clerks (1994)',
 'Don Juan DeMarco (1995)',
 'Disclosure (1994)',
 'Dream Man (1995)',
 'Drop Zone (1994)',
 'Destiny Turns on the Radio (1995)',
 'Death and the Maiden (1994)',
 'Dolores Claiborne (1995)',
 'Dumb & Dumber (Dumb and Dumber) (1994)',
 'Eat Drink Man Woman (Yin shi nan nu) (1994)',
 'Exotica (1994)',
 'Exit to Eden (1994)',
 'Ed Wood (1994)',
 'French Kiss (1995)',
 'Forget Paris (1995)',
 'Far From Home: The Adventures of Yellow Dog (1995)',
 'Goofy Movie; A (1995)',
 'Hideaway (1995)',
 'Fluke (1995)',
 'Farinelli: il castrato (1994)',
 'Gordy (1995)',
 'Gumby: The Movie (1995)',
 'The Glass Shield (1994)',
 'Hoop Dreams (1994)',
 'Heavenly Creatures (1994)',
 'Houseguest (1994)',
 'Immortal Beloved (1994)',
 'Heavyweights (Heavy Weights) (1995)',
 'Hunted; The (1995)',
 'I.Q. (1994)',
 'Interview with the Vampire: The Vampire Chronicles (1994)',
 'Jefferson in Paris (1995)',
 'Jerky Boys; The (1995)',
 'Junior (1994)',
 'Just Cause (1995)',
 "Kid in King Arthur's Court; A (1995)",
 'Kiss of Death (1995)',
 'Star Wars: Episode IV - A New Hope (1977)',
 'Little Women (1994)',
 'Little Princess; A (1995)',
 'Ladybird Ladybird (1994)',
 "Enfer; L' (1994)",
 'Like Water for Chocolate (Como agua para chocolate) (1992)',
 'Legends of the Fall (1994)',
 'Major Payne (1995)',
 'Little Odessa (1994)',
 'My Crazy Life (Mi vida loca) (1993)',
 'Love Affair (1994)',
 'Losing Isaiah (1995)',
 'Madness of King George; The (1994)',
 "Mary Shelley's Frankenstein (Frankenstein) (1994)",
 'Man of the House (1995)',
 'Mixed Nuts (1994)',
 'Milk Money (1994)',
 'Miracle on 34th Street (1994)',
 'Miami Rhapsody (1995)',
 'My Family (1995)',
 'Murder in the First (1995)',
 "Nobody's Fool (1994)",
 'Nell (1994)',
 'New Jersey Drive (1995)',
 'New York Cop (Nyû Yôku no koppu) (1993)',
 'Beyond Bedlam (1993)',
 'Nemesis 2: Nebula (1995)',
 'Nina Takes a Lover (1994)',
 'Natural Born Killers (1994)',
 'Only You (1994)',
 'Once Were Warriors (1994)',
 'Outbreak (1995)',
 'Léon: The Professional (a.k.a. The Professional) (Léon) (1994)',
 'Perez Family; The (1995)',
 "Pyromaniac's Love Story; A (1995)",
 'Pulp Fiction (1994)',
 'Panther (1995)',
 'Pushing Hands (Tui shou) (1992)',
 'Priest (1994)',
 'Quiz Show (1994)',
 'Picture Bride (Bijo photo) (1994)',
 'Queen Margot (Reine Margot; La) (1994)',
 'Quick and the Dead; The (1995)',
 'Roommates (1995)',
 'Ready to Wear (Pret-A-Porter) (1994)',
 'Three Colors: Red (Trois couleurs: Rouge) (1994)',
 'Three Colors: Blue (Trois couleurs: Bleu) (1993)',
 'Three Colors: White (Trzy kolory: Bialy) (1994)',
 'Red Firecracker; Green Firecracker (Pao Da Shuang Deng) (1994)',
 'Rent-a-Kid (1995)',
 'Relative Fear (1994)',
 'Stuart Saves His Family (1995)',
 'Swan Princess; The (1994)',
 'Secret of Roan Inish; The (1994)',
 'Specialist; The (1994)',
 'Stargate (1994)',
 'Santa Clause; The (1994)',
 'Shawshank Redemption; The (1994)',
 'Shallow Grave (1994)',
 'Suture (1993)',
 'Strawberry and Chocolate (Fresa y chocolate) (1993)',
 'Swimming with Sharks (1995)',
 'Sum of Us; The (1994)',
 "National Lampoon's Senior Trip (1995)",
 'To Live (Huozhe) (1994)',
 'Tank Girl (1995)',
 'Tales from the Crypt Presents: Demon Knight (1995)',
 'Star Trek: Generations (1994)',
 'Tales from the Hood (1995)',
 'Tom & Viv (1994)',
 'Village of the Damned (1995)',
 'Tommy Boy (1995)',
 'Vanya on 42nd Street (1994)',
 'Underneath (1995)',
 'Walking Dead; The (1995)',
 "What's Eating Gilbert Grape (1993)",
 'Virtuosity (1995)',
 'While You Were Sleeping (1995)',
 'War; The (1994)',
 'Double Happiness (1994)',
 "Muriel's Wedding (1994)",
 'Baby-Sitters Club; The (1995)',
 'Ace Ventura: Pet Detective (1994)',
 'Adventures of Priscilla; Queen of the Desert; The (1994)',
 'Backbeat (1993)',
 'Bitter Moon (1992)',
 'Bullets Over Broadway (1994)',
 'Clear and Present Danger (1994)',
 'Client; The (1994)',
 'Corrina; Corrina (1994)',
 'Crooklyn (1994)',
 'Crow; The (1994)',
 'Cobb (1994)',
 'Flintstones; The (1994)',
 'Forrest Gump (1994)',
 'Four Weddings and a Funeral (1994)',
 'Higher Learning (1995)',
 'I Like It Like That (1994)',
 'I Love Trouble (1994)',
 'It Could Happen to You (1994)',
 'Jungle Book; The (1994)',
 'Wonderful; Horrible Life of Leni Riefenstahl; The (Macht der Bilder: Leni Riefenstahl; Die) (1993)',
 'Lion King; The (1994)',
 'Little Buddha (1993)',
 "Wes Craven's New Nightmare (Nightmare on Elm Street Part 7: Freddy's Finale; A) (1994)",
 'Mask; The (1994)',
 'Maverick (1994)',
 'Mrs. Parker and the Vicious Circle (1994)',
 'Naked Gun 33 1/3: The Final Insult (1994)',
 'Paper; The (1994)',
 'Reality Bites (1994)',
 'Red Rock West (1992)',
 'Richie Rich (1994)',
 'Safe Passage (1994)',
 'River Wild; The (1994)',
 'Speed (1994)',
 'Speechless (1994)',
 'Timecop (1994)',
 'True Lies (1994)',
 'When a Man Loves a Woman (1994)',
 'Wolf (1994)',
 'Wyatt Earp (1994)',
 'Bad Company (1995)',
 'Man of No Importance; A (1994)',
 'S.F.W. (1994)',
 'Low Down Dirty Shame; A (1994)',
 'Boys Life (1995)',
 'Colonel Chabert; Le (1994)',
 'Faster Pussycat! Kill! Kill! (1965)',
 "Jason's Lyric (1994)",
 'Secret Adventures of Tom Thumb; The (1993)',
 'Street Fighter (1994)',
 'Coldblooded (1995)',
 'Desert Winds (1995)',
 'Fall Time (1995)',
 'Fear; The (1995)',
 'Frank and Ollie (1995)',
 'Girl in the Cadillac (1995)',
 'Homage (1995)',
 'Mirage (1995)',
 'Open Season (1996)',
 'Two Crimes (Dos crímenes) (1995)',
 'Brother Minister: The Assassination of Malcolm X (1994)',
 'Highlander III: The Sorcerer (a.k.a. Highlander: The Final Dimension) (1994)',
 'Federal Hill (1994)',
 'In the Mouth of Madness (1995)',
 '8 Seconds (1994)',
 'Above the Rim (1994)',
 'Addams Family Values (1993)',
 'Martin Lawrence: You So Crazy (1994)',
 'Age of Innocence; The (1993)',
 'Airheads (1994)',
 'Air Up There; The (1994)',
 'Another Stakeout (1993)',
 'Bad Girls (1994)',
 'Barcelona (1994)',
 'Being Human (1993)',
 'Beverly Hillbillies; The (1993)',
 'Beverly Hills Cop III (1994)',
 'Black Beauty (1994)',
 'Blink (1994)',
 'Blown Away (1994)',
 'Blue Chips (1994)',
 'Blue Sky (1994)',
 'Body Snatchers (1993)',
 'Boxing Helena (1993)',
 'Bronx Tale; A (1993)',
 'Cabin Boy (1994)',
 'Calendar Girl (1993)',
 "Carlito's Way (1993)",
 "City Slickers II: The Legend of Curly's Gold (1994)",
 'Clean Slate (1994)',
 'Cliffhanger (1993)',
 'Coneheads (1993)',
 'Color of Night (1994)',
 'Cops and Robbersons (1994)',
 'Cowboy Way; The (1994)',
 'Dangerous Game (1993)',
 'Dave (1993)',
 'Dazed and Confused (1993)',
 'Demolition Man (1993)',
 'Endless Summer 2; The (1994)',
 'Even Cowgirls Get the Blues (1993)',
 'Fatal Instinct (1993)',
 'Farewell My Concubine (Ba wang bie ji) (1993)',
 'Favor; The (1994)',
 'Fearless (1993)',
 'Fear of a Black Hat (1994)',
 'With Honors (1994)',
 'Flesh and Bone (1993)',
 "Widows' Peak (1994)",
 'For Love or Money (1993)',
 'Firm; The (1993)',
 'Free Willy (1993)',
 'Fresh (1994)',
 'Fugitive; The (1993)',
 'Geronimo: An American Legend (1993)',
 'Getaway; The (1994)',
 'Getting Even with Dad (1994)',
 'Go Fish (1994)',
 'Good Man in Africa; A (1994)',
 'Guilty as Sin (1993)',
 'Hard Target (1993)',
 'Heaven & Earth (1993)',
 'Hot Shots! Part Deux (1993)',
 'Live Nude Girls (1995)',
 'Englishman Who Went Up a Hill But Came Down a Mountain; The (1995)',
 'House of the Spirits; The (1993)',
 'House Party 3 (1994)',
 'Hudsucker Proxy; The (1994)',
 "I'll Do Anything (1994)",
 'In the Army Now (1994)',
 'In the Line of Fire (1993)',
 'In the Name of the Father (1993)',
 'Inkwell; The (1994)',
 "What's Love Got to Do with It? (1993)",
 'Jimmy Hollywood (1994)',
 'Judgment Night (1993)',
 'Jurassic Park (1993)',
 'Kalifornia (1993)',
 'Killing Zoe (1994)',
 'King of the Hill (1993)',
 'Lassie (1994)',
 'Last Action Hero (1993)',
 'Life with Mikey (1993)',
 'Lightning Jack (1994)',
 'M. Butterfly (1993)',
 'Made in America (1993)',
 'Malice (1993)',
 'Man Without a Face; The (1993)',
 'Manhattan Murder Mystery (1993)',
 'Menace II Society (1993)',
 'Executive Decision (1996)',
 'In the Realm of the Senses (Ai no corrida) (1976)',
 'What Happened Was... (1994)',
 'Much Ado About Nothing (1993)',
 'Mr. Jones (1993)',
 'Mr. Wonderful (1993)',
 'Mrs. Doubtfire (1993)',
 'Naked (1993)',
 'Next Karate Kid; The (1994)',
 'New Age; The (1994)',
 'No Escape (1994)',
 'North (1994)',
 'Orlando (1992)',
 'Perfect World; A (1993)',
 'Philadelphia (1993)',
 'Piano; The (1993)',
 'Poetic Justice (1993)',
 'Program; The (1993)',
 'Puppet Masters; The (1994)',
 'Radioland Murders (1994)',
 'Ref; The (1994)',
 'Remains of the Day; The (1993)',
 'Renaissance Man (1994)',
 'Rising Sun (1993)',
 'Road to Wellville; The (1994)',
 'RoboCop 3 (1993)',
 'Robin Hood: Men in Tights (1993)',
 'Romeo Is Bleeding (1993)',
 'Romper Stomper (1992)',
 'Ruby in Paradise (1993)',
 'Rudy (1993)',
 'Saint of Fort Washington; The (1993)',
 'Savage Nights (Nuits fauves; Les) (1992)',
 "Schindler's List (1993)",
 'Scout; The (1994)',
 'Searching for Bobby Fischer (1993)',
 'Second Best (1994)',
 'Secret Garden; The (1993)',
 'Serial Mom (1994)',
 'Shadow; The (1994)',
 'Shadowlands (1993)',
 'Short Cuts (1993)',
 'Simple Twist of Fate; A (1994)',
 'Sirens (1994)',
 'Six Degrees of Separation (1993)',
 'Sleepless in Seattle (1993)',
 'Sliver (1993)',
 'Blade Runner (1982)',
 'Son in Law (1993)',
 'So I Married an Axe Murderer (1993)',
 'Striking Distance (1993)',
 'Super Mario Bros. (1993)',
 'Surviving the Game (1994)',
 'Terminal Velocity (1994)',
 'Thirty-Two Short Films About Glenn Gould (1993)',
 'Threesome (1994)',
 'Nightmare Before Christmas; The (1993)',
 'Three Musketeers; The (1993)',
 'Tombstone (1993)',
 'Trial by Jury (1994)',
 'True Romance (1993)',
 'War Room; The (1993)',
 'Pagemaster; The (1994)',
 'Paris; France (1993)',
 'Beans of Egypt; Maine; The (1994)',
 'Killer (Bulletproof Heart) (1994)',
 'Welcome to the Dollhouse (1995)',
 'Germinal (1993)',
 'Chasers (1994)',
 'Cronos (1993)',
 'Naked in New York (1994)',
 'Kika (1993)',
 'Bhaji on the Beach (1993)',
 'Little Big League (1994)',
 'Slingshot; The (Kådisbellan) (1993)',
 'Wedding Gift; The (1994)',
 'Foreign Student (1994)',
 'Ciao; Professore! (Io speriamo che me la cavo) (1992)',
 'Spanking the Monkey (1994)',
 'Little Rascals; The (1994)',
 'Fausto (1993)',
 'Andre (1994)',
 'Escort; The (Scorta; La) (1993)',
 'Princess Caraboo (1994)',
 'Celluloid Closet; The (1995)',
 'Métisse (Café au Lait) (1993)',
 'Dear Diary (Caro Diario) (1994)',
 "I Don't Want to Talk About It (De eso no se habla) (1993)",
 'Brady Bunch Movie; The (1995)',
 'Home Alone (1990)',
 'Ghost (1990)',
 'Aladdin (1992)',
 'Terminator 2: Judgment Day (1991)',
 'Dances with Wolves (1990)',
 'Tough and Deadly (1995)',
 'Batman (1989)',
 'Silence of the Lambs; The (1991)',
 'Snow White and the Seven Dwarfs (1937)',
 'Beauty and the Beast (1991)',
 'Pinocchio (1940)',
 'Pretty Woman (1990)',
 'Window to Paris (Okno v Parizh) (1994)',
 'Wild Bunch; The (1969)',
 'Love and a .45 (1994)',
 "Wooden Man's Bride; The (Yan shen) (1994)",
 'Great Day in Harlem; A (1994)',
 'Bye Bye; Love (1995)',
 'Criminals (1996)',
 'One Fine Day (1996)',
 'Candyman: Farewell to the Flesh (1995)',
 'Century (1993)',
 'Fargo (1996)',
 'Homeward Bound II: Lost in San Francisco (1996)',
 'Heavy Metal (1981)',
 'Hellraiser: Bloodline (1996)',
 'Pallbearer; The (1996)',
 'Jane Eyre (1996)',
 'Loaded (1994)',
 'Bread and Chocolate (Pane e cioccolata) (1973)',
 'Aristocats; The (1970)',
 'Flower of My Secret; The (La flor de mi secreto) (1995)',
 'Two Much (1995)',
 'Ed (1996)',
 'Scream of Stone (Cerro Torre: Schrei aus Stein) (1991)',
 'My Favorite Season (1993)',
 'Modern Affair; A (1995)',
 'Asfour Stah (1990)',
 'Thin Line Between Love and Hate; A (1996)',
 'Last Supper; The (1995)',
 'Primal Fear (1996)',
 'Rude (1995)',
 'Carried Away (1996)',
 'All Dogs Go to Heaven 2 (1996)',
 'Land and Freedom (Tierra y libertad) (1995)',
 'Denise Calls Up (1995)',
 'Theodore Rex (1995)',
 'Family Thing; A (1996)',
 'Frisk (1995)',
 'Sgt. Bilko (1996)',
 'Jack and Sarah (1995)',
 'Girl 6 (1996)',
 'Diabolique (1996)',
 'Little Indian; Big City (Un indien dans la ville) (1994)',
 'Roula (1995)',
 'Peanuts - Die Bank zahlt alles (1996)',
 'Happy Weekend (1996)',
 'Nelly & Monsieur Arnaud (1995)',
 'Courage Under Fire (1996)',
 'Mission: Impossible (1996)',
 'Cold Fever (Á köldum klaka) (1995)',
 'Moll Flanders (1996)',
 'Superweib; Das (1996)',
 '301; 302 (301/302) (1995)',
 'Dragonheart (1996)',
 'And Nobody Weeps for Me (Und keiner weint mir nach) (1996)',
 "My Mother's Courage (Mutters Courage) (1995)",
 'Eddie (1996)',
 'Yankee Zulu (1994)',
 "Billy's Holiday (1995)",
 'Purple Noon (Plein soleil) (1960)',
 'August (1996)',
 'James and the Giant Peach (1996)',
 'Fear (1996)',
 'Kids in the Hall: Brain Candy (1996)',
 'Faithful (1996)',
 'Underground (1995)',
 'All Things Fair (Lust och fägring stor) (1995)',
 'Bloodsport 2 (a.k.a. Bloodsport II: The Next Kumite) (1996)',
 'Song of the Little Road (Pather Panchali) (1955)',
 'World of Apu; The (Apur Sansar) (1959)',
 'Mystery Science Theater 3000: The Movie (1996)',
 'Tarantella (1995)',
 'Space Jam (1996)',
 'Barbarella (1968)',
 'Hostile Intentions (1994)',
 'They Bite (1996)',
 'Some Folks Call It a Sling Blade (1993)',
 'Run of the Country; The (1995)',
 'Alphaville (Alphaville; une étrange aventure de Lemmy Caution) (1965)',
 'Coup de torchon (Clean Slate) (1981)',
 'Tigrero: A Film That Was Never Made (1994)',
 "Eye of Vichy; The (Oeil de Vichy; L') (1993)",
 'Windows (1980)',
 "It's My Party (1996)",

In [574]:
movies['title'] = cleaned_movies

In [575]:
movies.head()

,title,genres
movieId,,
1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
2,Jumanji (1995),Adventure|Children|Fantasy
3,Grumpier Old Men (1995),Comedy|Romance
4,Waiting to Exhale (1995),Comedy|Drama|Romance
5,Father of the Bride Part II (1995),Comedy

In [576]:
movies.to_csv('<file path>/<file name>.csv')

In [577]:
tag_data = pd.read_csv('<file path>/<file name>.csv', index_col='movieId')
tag_data.head()

         userId               tag   timestamp
movieId
260           3           classic  1439472355
260           3            sci-fi  1439472256
1732          4       dark comedy  1573943598
1732          4    great dialogue  1573943604
7569          4  so bad it's good  1573943455

In [578]:
# Removing commas for SQL database
tag_tags = tag_data['tag']
cleaned_tags = []
for tag in tag_tags:
    tag = str(tag)
    tag = tag.replace(',', '')
    cleaned_tags.append(tag)
cleaned_tags

['classic',
 'sci-fi',
 'dark comedy',
 'great dialogue',
 "so bad it's good",
 'unreliable narrators',
 'tense',
 'artificial intelligence',
 'philosophical',
 'tense',
 "so bad it's good",
 'cliche',
 'musical',
 'horror',
 'unpredictable',
 'Oscar (Best Supporting Actress)',
 'adventure',
 'anime',
 'ecology',
 'fantasy',
 'Hayao Miyazaki',
 'Miyazaki',
 'post-apocalyptic',
 'bah',
 'Clint Eastwood',
 'music',
 'art',
 'contemporary art',
 'documentary',
 'aliens',
 'amazing photography',
 'Director: James Cameron',
 'first contact',
 'James Cameron',
 'Michael Biehn',
 'sci-fi',
 'android(s)/cyborg(s)',
 'apocalypse',
 'Arnold Schwarzenegger',
 'artificial intelligence',
 'franchise',
 'terminator',
 'time travel',
 'James Cameron',
 'sci-fi',
 'science fiction',
 'sci-fi',
 'inferior sequel',
 'setting:London (UK) (future)',
 'unoriginal',
 'bad science',
 'good science',
 'Hans Zimmer',
 'philosophical issues',
 'sci-fi',
 'science fiction',
 'space',
 'space travel',
 'time-travel',
 'visually appealing',
 'bittersweet',
 'boring',
 'conversation',
 'dialogue driven',
 'loneliness',
 'love story',
 'philosophical',
 'philosophy',
 'quirky',
 'reflective',
 'romantic',
 'thought-provoking',
 'Vienna',
 'wistful',
 'American Civil War',
 'based on book',
 'bittersweet',
 'culture clash',
 'drama',
 'indians',
 'love story',
 'war',
 'western',
 'Buddhism',
 'China',
 'great cinematography',
 'JOURNEY OF SELF-DISCOVERY',
 'mountains',
 'traveling',
 'atmospheric',
 'based on a book',
 'Canada',
 'death',
 'Incest',
 'meditative',
 'melancholic',
 'Nudity (Full Frontal)',
 'small town',
 'wintry',
 'aging',
 'based on a play',
 'boring',
 'Drama',
 'friendship',
 'Morgan Freeman',
 'no action',
 'old age',
 'racism',
 'Southern theme',
 'USA',
 'bittersweet',
 'emotional',
 'heartwarming',
 'Holocaust',
 'Italy',
 'love',
 'Oscar (Best Foreign Language Film)',
 'Oscar Winner',
 'sentimental',
 'survival',
 'adventure',
 'fantasy',
 'music',
 'Natalie Portman',
 'robots',
 'sci-fi',
 'space',
 'Star Wars',
 'abortion',
 'based on a book',
 'charlize theron',
 'Drama',
 'Incest',
 'medicine',
 'orphans',
 'Tobey Maguire',
 'based on a book',
 'break-up',
 'Catherine Zeta-Jones',
 'funny',
 'relationships',
 'island',
 'SURVIVAL',
 'boring',
 'dogs',
 'drama',
 'multiple storylines',
 'action',
 'adventure',
 'aliens',
 'fantasy',
 'George Lucas',
 'robots',
 'romance',
 'sci-fi',
 'space',
 'Star Wars',
 'based on a book',
 'Drama',
 'family',
 'mystery',
 'powerful ending',
 'twist ending',
 'adapted from:book',
 'assassin',
 'assassination',
 'History',
 'interesting',
 'Southern Europe',
 'tense',
 'thriller',
 'bittersweet',
 'boring',
 'dialogue',
 'emotional',
 'Paris',
 'philosophical',
 'quirky',
 'romance',
 'romantic',
 'adultery',
 'biographical',
 'Biography',
 'blindness',
 'disability',
 'drug addiction',
 'drugs',
 'genius',
 'great acting',
 'history',
 'music',
 'music business',
 'musical',
 'rhythm & blues',
 'boring',
 'Catholicism',
 'child abuse',
 'drugs',
 'enigmatic',
 'Gay sex',
 'mistaken identity',
 'queer',
 'soccer',
 'spanish',
 'alcoholism',
 'complex characters',
 'confusing',
 'Germany',
 'loneliness',
 'love story',
 'Nudity (Full Frontal)',
 'biomedical ethics',
 'death',
 'disability',
 'emotional',
 'euthanasia',
 'FIGHTING THE SYSTEM',
 'meditative',
 'Oscar (Best Foreign Language Film)',
 'SUICIDE',
 'suicide attempt',
 'terminal illness',
 'touching',
 'true story',
 'boring',
 'deliberate',
 'nonsense',
 'philosophycal',
 'quiet',
 'quirky',
 'silent',
 'very little dialogue',
 'biopic',
 'character study',
 'death penalty',
 'gay',
 'journalism',
 'prison',
 'thought provoking',
 'writers',
 'based on a true story',
 'biography',
 'bittersweet',
 'Joaquin Phoenix',
 'love',
 'music',
 'music business',
 'true story',
 'Disturbing',
 'interesting',
 'murder mystery',
 'non-hollywood ending',
 'twist',
 'twist ending',
 'based on a true story',
 'simple',
 'Straight forward',
 'strong woman',
 'WOMEN DURING WARTIME',
 'World War II',
 'cynical',
 'disturbing',
 'drama',
 'family',
 'Nudity (Topless - Notable)',
 'Nudity (Topless)',
 'psychology',
 'reflective',
 'small town',
 'emotional',
 'epidemic',
 'husband-wife relationship',
 'romance',
 'science',
 'scientific research',
 'George Clooney',
 'lawyers',
 'based on a true story',
 'depressing',
 'disability',
 'hospital',
 'marriage',
 'thought-provoking',
 'touching',
 'true story',
 'bittersweet',
 'boring',
 'Jude Law',
 'Natalie Portman',
 'road movie',
 'soundtrack',
 'visually appealing',
 'alternate endings',
 'beautiful',
 'humanity',
 'quirky',
 'quirky style',
 'romance',
 'solitude',
 'awkward',
 'Barcelona',
 'love',
 'relationships',
 'romance',
 'threesome',
 'visually appealing',
 'congressman',
 'corruption',
 'journalism',
 'mistress',
 'murder',
 'newspaper',
 'political corruption',
 'politics',
 'secrets',
 'tense',
 'bittersweet',
 'Funny',
 'humorous',
 'love',
 'nonlinear',
 'relationships',
 'romance',
 'drama',
 'excellent script',
 'love',
 'mystery',
 'nostalgic',
 'revenge',
 'effects',
 'environmental',
 'music',
 'sci-fi',
 'thought-provoking',
 'action',
 'alternate reality',
 'drama',
 'psychology',
 'thought-provoking',
 'twist ending',
 'atmospheric',
 'based on a book',
 'cynical',
 'depressing',
 'disturbing',
 'dystopia',
 'emotional',
 'love story',
 'thought-provoking',
 'based on a true story',
 'complex characters',
 'drama',
 'Oscar (Best Picture)',
 'mindfuck',
 'sci-fi',
 'action',
 "Alzheimer's disease",
 'Animals',
 'genetics',
 'sci-fi',
 'thought-provoking',
 'touching',
 'virus',
 'adapted from:book',
 'bittersweet',
 'children',
 'cinematography',
 'fantasy',
 'nostalgic',
 'Paris',
 'robots',
 'visually appealing',
 'based on a true story',
 'campaign manager',
 'politics',
 'real life',
 'Fish',
 'food',
 'Ginza',
 'Japan',
 'Michelin',
 'sushi',
 'Tokyo',
 'Tsukiji',
 'disability',
 'drama',
 'humor',
 'nudity (full frontal)',
 'relationships',
 'sexuality',
 'static',
 'strange',
 'uncomfortable',
 'biography',
 'history',
 'oscar (best directing)',
 'US President',
 'president; butler',
 'Ferrari',
 'Formula 1',
 'great skill',
 'interesting characters',
 'racing',
 'sports',
 'unpredictable',
 'depressing',
 'happy ending',
 'middle-aged protagonist',
 'warm',
 'captain',
 'ocean',
 'suspense',
 'true story',
 'disease',
 'Matthew McConaughey',
 'medical',
 'based on a book',
 'based on a true story',
 'bittersweet',
 'dramatic comedy',
 'sad',
 'story',
 'true story',
 'adapted from:book',
 'narration',
 'touching',
 'World War II',
 'atmospheric',
 'boring',
 'cats',
 'depressing',
 'folk music',
 'New York City',
 'Nudity (Full Frontal)',
 'Nudity (Topless)',
 'repetitive',
 'Wall Street',
 'artificial intelligence',
 'bittersweet',
 'Human Computer Interaction',
 'Joaquin Phoenix',
 'landscape',
 'letters',
 'loneliness',
 'meaning of life',
 'original plot',
 'philosophical',
 'psychology',
 'sad',
 'thought-provoking',
 'Nudity (Topless)',
 'repeating',
 'simple',
 'Afghanistan',
 'friendship',
 'seals',
 'true story',
 'naration',
 'Nudity (Full Frontal - Notable)',
 'sexuality',
 'story',
 'based on a true story',
 'George Clooney',
 'german sync',
 'matt damon',
 'Lars von Trier',
 'Nudity (Full Frontal - Notable)',
 'pornography',
 'sexuality',
 'Unexpected Ending',
 'quirky',
 'visually appealing',
 'interesting ideea',
 'original',
 'philosophical issues',
 'sentimental',
 'space',
 'spectacle',
 'thought-provoking',
 'time-travel',
 'wormhole',
 'espionage',
 'Jean Dujardin',
 'love story',
 'bitterswee',
 'music',
 'new york',
 'romance',
 'soundtrack',
 'story',
 'action',
 'future',
 'original plot',
 'sci-fi',
 'time loop',
 'time travel',
 'Tom Cruise',
 'war',
 'dialogue',
 'plot holes',
 'ridiculous dialogue',
 'robots',
 'transformers',
 'weak story',
 'drama',
 'education',
 'good acting',
 'jazz',
 'motivation',
 'perfectionism',
 'psychological',
 'adultery',
 'Ben Affleck',
 'false accusation',
 'good adaptation',
 'Infidelity',
 'marriage',
 'meticulous',
 'mindfuck',
 'murder',
 'Psychopathy',
 'unpredictable',
 'action',
 'emotional',
 'genetics',
 'Matt Reeves',
 'relationships',
 'virus',
 'Action',
 'comic',
 'fantasy',
 'sci-fi',
 'space',
 'superheroes',
 'talking animals',
 'Vin Diesel',
 'counterespionage',
 'slow',
 'based on a book',
 'Law',
 'acting',
 'action',
 'Brad Pitt',
 'David Ayer',
 'drama',
 'sentimental',
 'to much war',
 'war hero',
 'World War II',
 'artificial intelligence',
 'Drama',
 'Manipulations',
 'philosophical',
 'sci-fi',
 'technology',
 'thought provoking',
 'mental illness',
 'surprising',
 'twisted end',
 'code breaking',
 'Computers',
 'cryptography',
 'genius',
 'history',
 'informatics',
 'mathematics',
 'World War II',
 'love',
 'physics',
 'science',
 'Stephen Hawking',
 'True story',
 'image',
 'Olga Kurylenko',
 'story',
 'based on book',
 'Improvisation',
 'mars',
 'matt damon',
 'NASA',
 'Near Future',
 'predictible',
 'sci-fi',
 'scientific',
 'Space',
 'Survival Instinct',
 'boring',
 'no action',
 'romance',
 'war',
 'adoption',
 'Oscar Nominee: Best Picture',
 'dreamlike',
 'Fantasy',
 'imagination',
 'surreal',
 'surrealism',
 'truth vs. fantasy',
 'gay',
 'gay romance',
 'disturbing',
 'surrealism',
 'action',
 'adventure',
 'fantasy',
 'space adventure',
 'overcoming obstacles',
 'space adventure',
 'teamwork',
 'Coen Brothers',
 'dark comedy',
 'quirky',
 'witty',
 'philosophy',
 'surreal',
 'based on a true story',
 'smart',
 'Tom Hanks',
 '4th wall',
 'crude language',
 'parody',
 'soulless',
 'cult film',
 "so bad it's good",
 'unintentional comedy',
 'dark',
 'missing children',
 'torture',
 'Ewan McGregor',
 'Jar Jar Binks',
 'robots',
 'sci-fi',
 'Tom Cruise',
 'AI',
 'artificial intelligence',
 'robots',
 'karate',
 'emotional',
 'inspiring',
 'purpose in life',
 'summer',
 'ambush',
 'England',
 'Romans',
 'violent',
 'dark',
 'television',
 'violent',
 'Michael Moore',
 'propaganda',
 'metafiction',
 'Christopher Nolan',
 'artificial intelligence',
 'turing test',
 'impressive visuals',
 'magic',
 'mystery',
 'tang dynasty',
 'aliens',
 'Nicolas Cage',
 'sci-fi',
 'art',
 'manipulation',
 'psychology',
 'free running',
 'no story',
 'parkour',
 'funny',
 'funny',
 'funny',
 'running',
 'abduction',
 'bound',
 'canada',
 'dark humor',
 'gagged',
 'kidnapping',
 'montreal',
 'nightmares',
 'small cast',
 'twist ending',
 'twisted',
 'bad ending',
 'death',
 'Nudity (Topless - Brief)',
 'Oscar (Best Actor)',
 'Oscar (Best Actress)',
 'Oscar (Best Supporting Actress)',
 'want to see again',
 'Disturbing',
 'Sick',
 'animation',
 'big budget',
 'Christian',
 'Christmas',
 'family',
 'Tom Hanks',
 'starts well but fails you in the middle till the end',
 'film noir',
 'low budget',
 'decline of civilization',
 'future',
 'prophetic',
 'space',
 'sex with the enemy',
 'action',
 'assassin',
 'brutal violence',
 'gun fu',
 'murder',
 'plot twist',
 'stylized violence',
 'TOO much violence',
 'twist',
 'Amazing!',
 'anti-hero',
 'bad ending',
 'better than expected',
 'Charlize Theron',
 'innovative',
 'movie to see',
 'plot twist',
 'superhero',
 'Will Smith',
 'enjoyable',
 'good laughs',
 'twist',
 'Unexpected Ending',
 'chick flick',
 'space program',
 'stephan king',
 'Special effects',
 'off-beat comedy',
 'Disney',
 'Special effects',
 'netflixq',
 'atmospheric',
 'based on a book',
 'cult classic',
 'homoerotic subtext',
 'anti-romantic ending',
 'racist',
 'atmospheric',
 'dreamlike',
 'great soundtrack',
 'original',
 'philosophy',
 'psychology',
 'quirky',
 'sci-fi',
 'stylized',
 'surreal',
 'thought-provoking',
 'time travel',
 'weird',
 'Studio Ghibli',
 'black comedy',
 'comedy',
 'friendship',
 'awesome',
 'colorful',
 'humor',
 'Jeff Goldblum',
 'Taika Waititi',
 'unconventional',
 'Heartbreaking',
 'Sad',
 'Sad',
 'classic sci-fi',
 'good vs evil',
 'funny',
 'great acting',
 'touching',
 'brilliant',
 'dark',
 'scary',
 'atmospheric',
 'ghosts',
 'scary',
 'Bisexual',
 'Canadian',
 'dark comedy',
 'Distopian',
 'Indy',
 'Lgbt',
 'Mystery',
 'Thomas Gibson',
 'aliens',
 'oldie but goodie',
 'scifi cult',
 'space',
 'space adventure',
 'assassin',
 'Black comedy',
 'cult film',
 'dark comedy',
 'Quentin Tarantino',
 'stylized',
 'violence',
 'classic',
 'courtroom',
 'courtroom drama',
 'group psychology',
 'Old',
 'social commentary',
 'thought-provoking',
 'college',
 'Geeks',
 'nerds',
 'smart comedy',
 'teen comedy',
 'witty',
 'dystopia',
 'dystopic future',
 'future',
 'futuristic',
 'genetic selection',
 'genetics',
 'intelligent',
 'powerful ending',
 'space travel',
 'thought-provoking',
 'Uma Thurman',
 'underdog',
 'visually appealing',
 'alternate reality',
 'dark comedy',
 'dystopia',
 'Jim Carrey',
 'mindfuck',
 'poignant',
 'reality TV',
 'small town',
 'based on a book',
 'Bisexuality',
 'Great soundtrack',
 'Historic',
 'Sexy',
 'black comedy',
 'comedy',
 'conspiracy',
 'corruption',
 'cover up',
 'political',
 'politics',
 'satire',
 'unique',
 'US President',
 'crude humor',
 'sexual',
 'stupid',
 'cliche',
 'coming of age',
 'coming-of-age',
 'cult film',
 'great music',
 'John Hughes',
 'overdramatic',
 'school drama',
 'teen',
 'teen movie',
 'Bromance',
 'college',
 'Comedy',
 'black comedy',
 'cynical',
 'dark comedy',
 'high school',
 'Reese Witherspoon',
 'satire',
 'teen',
 'comedy',
 'funny',
 'high school',
 'sexuality',
 'stereotypes',
 'teen comedy',
 'Teen movie',
 'menage a trois',
 'polygamy',
 'guilty pleasure',
 'high school',
 'teen movie',
 '1980s',
 'breaking the fourth wall',
 'charming',
 'comedy',
 'High School',
 'rebellion',
 'teen movie',
 'complicated',
 'mindfuck',
 'violence',
 'comedy',
 'funny',
 'funny moments',
 'mean spirited',
 'stupid',
 'tolkien',
 'cloning',
 'dystopia',
 'future',
 'genetics',
 'immortality',
 'comedy',
 'funny',
 'geeks',
 'hilarious',
 'nerds',
 'sex',
 'sex comedy',
 'steve carell',
 'Jonah Hill',
 'marijuana',
 'Quotable',
 'stoner',
 'Stoner Movie',
 'video game testers',
 'video games',
 'dark comedy',
 'decline of civilization',
 'dystopia',
 'future',
 'social commentary',
 'thought provoking',
 'Underrated',
 'Coming of age',
 'Coming-Of-Age',
 'Emma Stone',
 'friendship',
 'funny',
 'high school',
 'HIGH SCHOOL LIFE',
 'nerds',
 'Teen movie',
 'amy poehler',
 'teacher',
 'comedy',
 'Hawaii',
 'hilarious',
 'Jason Segel',
 'Kristen Bell',
 'Mila Kunis',
 'Paul Rudd',
 'CIA',
 'cynical',
 'father daughter relationship',
 'gritty',
 'happy ending',
 'human trafficking',
 'kidnapping',
 'buddy movie',
 'funny',
 'silly',
 'spoof',
 'subtle humor',
 'Will Ferrell',
 'awesome soundtrack',
 'comedy',
 'cultural references',
 'geek',
 'geeks',
 'geeky',
 'video games',
 'high school',
 'protagonist is a teacher',
 'teacher',
 'black comedy',
 'jason bateman',
 'Jennifer Aniston',
 'murder',
 'weak ending',
 'bromance',
 'Channing Tatum',
 'comedy',
 'drugs',
 'high school',
 'self-aware',
 'undercover cops',
 'election',
 'funny',
 'politics',
 'satire',
 'brother sister incest',
 'comedy',
 'teacher student sex',
 'Amy Poehler',
 'Cobie Smulders',
 'Indy',
 'Rom Com',
 'Self deprecating',
 'absurd',
 'bromance',
 'buddy movie',
 'comedy',
 'funny',
 'Propaganda',
 'satire',
 'Absurd',
 'Cross generational',
 ...]

In [579]:
tag_data['tag'] = cleaned_tags

In [580]:
tag_data.head()

         userId               tag   timestamp
movieId
260           3           classic  1439472355
260           3            sci-fi  1439472256
1732          4       dark comedy  1573943598
1732          4    great dialogue  1573943604
7569          4  so bad it's good  1573943455

In [581]:
tag_data.to_csv('<file path>/<file name>.csv')