In [1]:
import csv
import json
import pandas as pd

In [2]:
df = pd.read_csv("../Resources/movie_df_with_labels.csv", index_col=["Unnamed: 0"])
df.head()

,adult,budget,original_language,popularity,revenue,runtime,status,title,vote_average,vote_count,...,genre_horror,genre_music,genre_mystery,genre_romance,genre_science_fiction,genre_tv_movie,genre_thriller,genre_war,genre_western,group
0,False,0,en,8.387519,76578911,106.0,Released,Father of the Bride Part II,5.7,173,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
1,False,35000000,en,5.231580,64350171,106.0,Released,Sudden Death,5.5,174,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,3
2,False,58000000,en,14.686036,352194034,130.0,Released,GoldenEye,6.6,1194,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2
3,False,62000000,en,6.318445,107879496,106.0,Released,The American President,6.5,199,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3
4,False,0,en,5.430331,0,88.0,Released,Dracula: Dead and Loving It,5.7,210,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [3]:
df.columns

Index(['adult', 'budget', 'original_language', 'popularity', 'revenue',
       'runtime', 'status', 'title', 'vote_average', 'vote_count',
       'genre_action', 'genre_adventure', 'genre_animation', 'genre_comedy',
       'genre_crime', 'genre_documentary', 'genre_drama', 'genre_family',
       'genre_fantasy', 'genre_foreign', 'genre_history', 'genre_horror',
       'genre_music', 'genre_mystery', 'genre_romance',
       'genre_science_fiction', 'genre_tv_movie', 'genre_thriller',
       'genre_war', 'genre_western', 'group'],
      dtype='object')

In [4]:
genres = df[['genre_action', 'genre_adventure', 'genre_animation', 'genre_comedy',
       'genre_crime', 'genre_documentary', 'genre_drama', 'genre_family',
       'genre_fantasy', 'genre_foreign', 'genre_history', 'genre_horror',
       'genre_music', 'genre_mystery', 'genre_romance',
       'genre_science_fiction', 'genre_tv_movie', 'genre_thriller',
       'genre_war', 'genre_western']]
genres

,genre_action,genre_adventure,genre_animation,genre_comedy,genre_crime,genre_documentary,genre_drama,genre_family,genre_fantasy,genre_foreign,genre_history,genre_horror,genre_music,genre_mystery,genre_romance,genre_science_fiction,genre_tv_movie,genre_thriller,genre_war,genre_western
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45408,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45409,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45410,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
45411,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
45412,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
genres_bool = genres.replace({0.0: False, 1.0: True})
genres_bool['genre'] = genres_bool.apply(lambda row: ' '.join([col.split('_')[1] for col in genres_bool.columns if row[col]]), axis=1)
# genres['genre'] = genres['genre'].replace({'genre_horror': 'Horror', 'genre_music': 'Music', 'genre_mystery': 'Mystery', 'genre_romance': 'Romance', 'genre_science_fiction': 'Science Fiction', 'genre_thriller': 'Thriller', 'genre_war': 'War', 'genre_western': 'Western'})
# genres['genre'] = genres['genre'].replace(['genre_horror', 'genre_music', 'genre_mystery', 'genre_romance', 'genre_science_fiction', 'genre_thriller', 'genre_war', 'genre_western'], ['Horror', 'Music', 'Mystery', 'Romance', 'Science Fiction', 'Thriller', 'War', 'Western'])
genres_bool

,genre_action,genre_adventure,genre_animation,genre_comedy,genre_crime,genre_documentary,genre_drama,genre_family,genre_fantasy,genre_foreign,...,genre_horror,genre_music,genre_mystery,genre_romance,genre_science_fiction,genre_tv_movie,genre_thriller,genre_war,genre_western,genre
0,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,comedy
1,True,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,action adventure thriller
2,True,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,action adventure thriller
3,False,False,False,True,False,False,True,False,False,False,...,False,False,False,True,False,False,False,False,False,comedy drama romance
4,False,False,False,True,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,comedy horror
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45408,False,False,False,True,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,comedy fantasy
45409,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,documentary
45410,False,False,False,False,True,False,True,False,False,False,...,False,False,False,False,False,False,True,False,False,crime drama thriller
45411,True,False,False,False,False,False,True,False,False,False,...,False,False,False,True,False,False,False,False,False,action drama romance
45412,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,drama

In [6]:
df.drop(columns=genres, inplace=True)
df['genre'] = genres_bool['genre']
df['genre'] = df['genre'].tolist()
df.head()

,adult,budget,original_language,popularity,revenue,runtime,status,title,vote_average,vote_count,group,genre
0,False,0,en,8.387519,76578911,106.0,Released,Father of the Bride Part II,5.7,173,3,comedy
1,False,35000000,en,5.231580,64350171,106.0,Released,Sudden Death,5.5,174,3,action adventure thriller
2,False,58000000,en,14.686036,352194034,130.0,Released,GoldenEye,6.6,1194,2,action adventure thriller
3,False,62000000,en,6.318445,107879496,106.0,Released,The American President,6.5,199,3,comedy drama romance
4,False,0,en,5.430331,0,88.0,Released,Dracula: Dead and Loving It,5.7,210,0,comedy horror

In [7]:
df.genre[1]

'action adventure thriller'

In [8]:
year_df = pd.read_csv("../../Movies_Master_DB/movies_merged.csv", usecols=['release_date'])
df['release_date'] = year_df['release_date'].str.split('-').str[0]
df.head()

,adult,budget,original_language,popularity,revenue,runtime,status,title,vote_average,vote_count,group,genre,release_date
0,False,0,en,8.387519,76578911,106.0,Released,Father of the Bride Part II,5.7,173,3,comedy,1995
1,False,35000000,en,5.231580,64350171,106.0,Released,Sudden Death,5.5,174,3,action adventure thriller,1995
2,False,58000000,en,14.686036,352194034,130.0,Released,GoldenEye,6.6,1194,2,action adventure thriller,1995
3,False,62000000,en,6.318445,107879496,106.0,Released,The American President,6.5,199,3,comedy drama romance,1995
4,False,0,en,5.430331,0,88.0,Released,Dracula: Dead and Loving It,5.7,210,0,comedy horror,1995

In [9]:
website_df = df[['title','genre','release_date','popularity','vote_average','vote_count','runtime','original_language','group']]

In [10]:
website_df = website_df.loc[website_df['group'] == 0]

In [11]:
website_df['popularity'] = website_df['popularity'].round(2)

In [12]:
website_df.drop(columns=['group'], inplace=True)

In [13]:
website_df.columns

Index(['title', 'genre', 'release_date', 'popularity', 'vote_average',
       'vote_count', 'runtime', 'original_language'],
      dtype='object')

In [14]:
master_df=pd.read_csv("../../Movies_Master_DB/movies_merged.csv", usecols=['revenue','budget'])
website_df['revenue'] = master_df['revenue']
website_df['budget'] = master_df['budget']
website_df.rename(columns={'vote_average': 'rating'}, inplace=True)

In [15]:
website_df = website_df.drop(columns=['vote_count','popularity'])
website_df.columns

Index(['title', 'genre', 'release_date', 'rating', 'runtime',
       'original_language', 'revenue', 'budget'],
      dtype='object')

In [16]:
website_df = website_df[['title', 'genre', 'rating', 'release_date', 'runtime', 'revenue','budget','original_language']]

In [17]:
website_df.sort_values(by=['rating'], ascending=False, inplace=True)
website_df.head()

,title,genre,rating,release_date,runtime,revenue,budget,original_language
11353,First Round Down,action comedy,10.0,2017,0.0,0,0,en
10735,Nick Swardson: Taste It,comedy,10.0,2015,68.0,0,0,en
10973,The Reagan Show,documentary,10.0,2017,75.0,0,0,en
11123,In Search of Ancient Astronauts,documentary,10.0,1973,0.0,0,0,en
36981,Joe Cocker - Mad Dogs & Englishmen,documentary music,10.0,1971,117.0,0,0,en

In [18]:
website_df.set_index('title', inplace=True)
website_test = website_df.head(50)
website_final = website_df.head(2000)
genre_group = website_df.query('genre == "action adventure animation comedy crime documentary drama family fantasy foreign history horror music mystery romance science tv thriller war western"')

In [19]:
def genre_shrink(x):
    x = x.replace('action adventure animation comedy crime documentary drama family fantasy foreign history horror music mystery romance science tv thriller war western', 'action comedy drama family thriller')
    return x

website_final['genre'].replace('action adventure animation comedy crime documentary drama family fantasy foreign history horror music mystery romance science tv thriller war western', 'action comedy drama family thriller')

# maps = {}
# genre_group.map(lambda x: x.replace({'genre':'action adventure animation comedy crime documentary drama family fantasy foreign history horror music mystery romance science tv thriller war western'}, {'genre':'action comedy drama family thriller'}))

title
First Round Down                                                action comedy
Nick Swardson: Taste It                                                comedy
The Reagan Show                                                   documentary
In Search of Ancient Astronauts                                   documentary
Joe Cocker - Mad Dogs & Englishmen                          documentary music
                                                        ...
The Maker                                                     animation drama
Madaari                                                              thriller
JohnnyExpress                                        animation comedy science
The Life and Death of Colonel Blimp                  comedy drama romance war
Green Snake                            action fantasy foreign romance science
Name: genre, Length: 2000, dtype: object

In [20]:
website_final['genre'].replace('action adventure animation comedy crime documentary drama family fantasy foreign history horror music mystery romance science tv thriller war western', 'action comedy drama family thriller')
website_final['genre'].value_counts()

genre
documentary                                                                                                                                              375
drama                                                                                                                                                    254
action adventure animation comedy crime documentary drama family fantasy foreign history horror music mystery romance science tv thriller war western    212
comedy                                                                                                                                                   173
drama romance                                                                                                                                             65
                                                                                                                                                        ...
adventure animation family fantasy                                                                                                                         1
action drama history war                                                                                                                                   1
comedy mystery romance                                                                                                                                     1
animation drama war                                                                                                                                        1
action fantasy foreign romance science                                                                                                                     1
Name: count, Length: 290, dtype: int64

In [21]:
website_final.replace("action adventure animation comedy crime documentary drama family fantasy foreign history horror music mystery romance science tv thriller war western", "action comedy drama family thriller", inplace=True)
website_final['genre'].value_counts()

/var/folders/pq/c8tns78d3ng29nzcyk_1j4fw0000gn/T/ipykernel_3801/863560708.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  website_final.replace("action adventure animation comedy crime documentary drama family fantasy foreign history horror music mystery romance science tv thriller war western", "action comedy drama family thriller", inplace=True)

genre
documentary                               375
drama                                     254
action comedy drama family thriller       212
comedy                                    173
drama romance                              65
                                         ...
adventure animation family fantasy          1
action drama history war                    1
comedy mystery romance                      1
animation drama war                         1
action fantasy foreign romance science      1
Name: count, Length: 290, dtype: int64

In [22]:
# website_test.to_csv("assets/resources/movie_test.csv")
website_final.to_csv("assets/resources/movie_df_for_website.csv")